"use client";

import { useState } from "react";
import { inferFilename, langToExt, isSolidity, LANG_COLOR } from "../artifacts";

// Open a single code file in StackBlitz via a POST form (no SDK needed).
function openStackBlitz(filename: string, code: string, lang: string) {
  const isReact = lang === "tsx" || lang === "jsx";
  const isTs = lang === "ts" || lang === "typescript";
  const isHtml = lang === "html";
  const template = isReact ? "create-react-app" : isTs ? "typescript" : "javascript";
  const path = isReact ? `src/App.${lang === "jsx" ? "js" : "tsx"}` : isHtml ? "index.html" : filename;

  const form = document.createElement("form");
  form.method = "POST";
  form.action = "https://stackblitz.com/run";
  form.target = "_blank";
  form.style.display = "none";

  const add = (name: string, value: string) => {
    const input = document.createElement("input");
    input.type = "hidden";
    input.name = name;
    input.value = value;
    form.appendChild(input);
  };
  add("project[title]", filename);
  add("project[description]", "Generated by Blue Chat");
  add("project[template]", template);
  add(`project[files][${path}]`, code);

  document.body.appendChild(form);
  form.submit();
  form.remove();
}

// Open Solidity in the Remix IDE — it loads a file from the #code= hash param.
function openRemix(code: string) {
  const b64 = btoa(unescape(encodeURIComponent(code)));
  window.open(`https://remix.ethereum.org/#code=${b64}`, "_blank", "noopener,noreferrer");
}

export default function ArtifactCard({ lang, code }: { lang: string; code: string }) {
  const [copied, setCopied]   = useState(false);
  const [preview, setPreview] = useState(false);
  const [saved, setSaved]     = useState(false);

  const l        = lang.toLowerCase();
  const filename = inferFilename(code, l);
  const color    = LANG_COLOR[l] ?? "#64748B";
  const allLines = code.split("\n");
  const previewLines = allLines.slice(0, 5);
  const hiddenCount  = Math.max(0, allLines.length - previewLines.length);

  const isHtml  = l === "html";
  const isSol   = isSolidity(l);
  const isJsLike = ["tsx", "jsx", "ts", "js", "typescript", "javascript"].includes(l);
  // StackBlitz opens web code (HTML + JS/TS/React); Solidity → Remix; others copy-only.
  const canStackBlitz = isJsLike || isHtml;

  function copy() {
    navigator.clipboard?.writeText(code).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    });
  }

  function download() {
    const blob = new Blob([code], { type: "text/plain;charset=utf-8" });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement("a");
    a.href     = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  }

  // Save to Projects — persisted in localStorage so the user can revisit
  // generated code (read by a future /app/projects view). Newest first, capped.
  function saveToProjects() {
    try {
      const KEY = "blueagent:projects";
      const list = JSON.parse(localStorage.getItem(KEY) || "[]");
      const arr = Array.isArray(list) ? list : [];
      arr.unshift({
        id: `proj_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`,
        name: filename,
        type: langToExt(l),
        language: l,
        created: Date.now(),
        code,
      });
      localStorage.setItem(KEY, JSON.stringify(arr.slice(0, 100)));
      setSaved(true);
      setTimeout(() => setSaved(false), 1800);
    } catch { /* storage blocked */ }
  }

  return (
    <div className="my-4 rounded-2xl overflow-hidden border border-[#1A1A2E] bg-[#0d0d12]">
      {/* Header: filename · lang badge · copy */}
      <div className="flex items-center gap-2 px-4 py-2.5 border-b border-[#1A1A2E]">
        <span className="text-[13px]">📄</span>
        <span className="font-mono text-[12px] text-slate-200 truncate flex-1">{filename}</span>
        <span
          className="font-mono text-[9px] px-2 py-0.5 rounded uppercase tracking-wider shrink-0"
          style={{ color, background: `${color}1a`, border: `1px solid ${color}40` }}
        >
          {l}
        </span>
        <button
          onClick={copy}
          className="font-mono text-[10px] text-slate-500 hover:text-[#4FC3F7] transition-colors shrink-0"
        >
          {copied ? "copied ✓" : "copy"}
        </button>
      </div>

      {/* Code preview — first 5 lines */}
      <pre className="px-4 py-3.5 overflow-x-auto bg-[#070710]">
        <code className="font-mono text-[12px] text-slate-300 leading-relaxed">{previewLines.join("\n")}</code>
        {hiddenCount > 0 && (
          <div className="font-mono text-[11px] text-slate-600 mt-2">+ {hiddenCount} more line{hiddenCount !== 1 ? "s" : ""}</div>
        )}
      </pre>

      {/* HTML live preview (sandboxed iframe) */}
      {isHtml && preview && (
        <div className="border-t border-[#1A1A2E] bg-white">
          <iframe
            title={filename}
            srcDoc={code}
            sandbox="allow-scripts"
            className="w-full block"
            style={{ height: 400, border: "none" }}
          />
        </div>
      )}

      {/* Footer actions */}
      <div className="flex flex-wrap gap-2 px-4 py-3 border-t border-[#1A1A2E]">
        {isHtml && (
          <button
            onClick={() => setPreview((p) => !p)}
            className="font-mono text-[11px] px-3 py-1.5 rounded-lg border border-[#4FC3F7]/30 text-[#4FC3F7] hover:bg-[#4FC3F7]/10 transition-colors"
          >
            {preview ? "Hide Preview" : "Preview"}
          </button>
        )}
        <button
          onClick={download}
          className="font-mono text-[11px] px-3 py-1.5 rounded-lg border border-[#1A1A2E] text-slate-400 hover:text-white hover:border-[#4FC3F7]/40 transition-colors"
        >
          Download
        </button>
        <button
          onClick={saveToProjects}
          className="font-mono text-[11px] px-3 py-1.5 rounded-lg border border-[#34D399]/30 text-[#34D399] hover:bg-[#34D399]/10 transition-colors"
        >
          {saved ? "Saved ✓" : "Save"}
        </button>
        {isSol && (
          <button
            onClick={() => openRemix(code)}
            className="font-mono text-[11px] px-3 py-1.5 rounded-lg border border-[#1A1A2E] text-slate-400 hover:text-white hover:border-[#627EEA]/50 transition-colors"
          >
            Open in Remix ↗
          </button>
        )}
        {canStackBlitz && (
          <button
            onClick={() => openStackBlitz(filename, code, l)}
            className="font-mono text-[11px] px-3 py-1.5 rounded-lg border border-[#1A1A2E] text-slate-400 hover:text-white hover:border-[#4FC3F7]/40 transition-colors"
          >
            Open in StackBlitz ↗
          </button>
        )}
      </div>
    </div>
  );
}
