// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import { Test, console } from "forge-std/Test.sol";
import { MerkleDistributor } from "../MerkleDistributor.sol";
import { IERC20 } from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import { Ownable } from "@openzeppelin/contracts/access/Ownable.sol";

/**
 * Minimal 18-decimal ERC-20. Local to the test so the distributor's tests do
 * not depend on whatever mock a library happens to ship.
 */
contract MockERC20 is IERC20 {
    string public name = "New Blue Agent";
    string public symbol = "NEW";
    uint8 public constant decimals = 18;
    uint256 public totalSupply;
    mapping(address => uint256) public balanceOf;
    mapping(address => mapping(address => uint256)) public allowance;

    function mint(address to, uint256 amount) external {
        balanceOf[to] += amount;
        totalSupply += amount;
        emit Transfer(address(0), to, amount);
    }

    function transfer(address to, uint256 amount) external returns (bool) {
        balanceOf[msg.sender] -= amount;
        balanceOf[to] += amount;
        emit Transfer(msg.sender, to, amount);
        return true;
    }

    function approve(address spender, uint256 amount) external returns (bool) {
        allowance[msg.sender][spender] = amount;
        emit Approval(msg.sender, spender, amount);
        return true;
    }

    function transferFrom(address from, address to, uint256 amount) external returns (bool) {
        allowance[from][msg.sender] -= amount;
        balanceOf[from] -= amount;
        balanceOf[to] += amount;
        emit Transfer(from, to, amount);
        return true;
    }
}

/**
 * MerkleDistributor tests.
 *
 * Two distinct things are being proved here, and it is worth keeping them
 * apart because only the second one can catch the failure that actually
 * threatens this system:
 *
 *   A. THE CONTRACT AGREES WITH ITSELF. Trees built by `_buildTree` below,
 *      proofs from `_getProof`, verified by `claim`. Covers the state machine:
 *      double claims, bad proofs, the bitmap, the sweep timelock, ownership.
 *      Necessary, but circular — a wrong leaf formula would pass every one of
 *      these tests, because the same wrong formula generated the tree.
 *
 *   B. THE CONTRACT AGREES WITH THE SCRIPT THAT WILL ACTUALLY FEED IT.
 *      `test_ClaimsAgainstRootFromTypeScriptBuilder` hardcodes the root and
 *      two proofs produced by running the real `scripts/build-merkle.ts` over
 *      `scripts/fixtures/claim-allocations.fixture.csv`. Nothing in Solidity
 *      generated those bytes. If the on-chain leaf encoding ever drifts from
 *      the openzeppelin/merkle-tree package's, this is the only test in the
 *      repository that fails — and that drift is exactly the mistake that ships a
 *      contract on which every real claim reverts.
 *
 * The fixture root is regenerated by `npm run merkle:build -- <fixture>`, and
 * `npm run test:merkle` pins the same value from the TypeScript side, so the
 * two suites cross-check each other.
 */
contract MerkleDistributorTest is Test {
    MockERC20 internal token;
    MerkleDistributor internal dist;

    address internal owner = address(0xB10E);
    address internal alice = address(0xA11CE);
    address internal bob = address(0xB0B);
    address internal relayer = address(0xDEA1E7);

    uint256 internal constant ALICE_AMOUNT = 1_000e18;
    uint256 internal constant BOB_AMOUNT = 1;          // 1 wei — the dust case
    uint256 internal constant TOTAL = ALICE_AMOUNT + BOB_AMOUNT;

    bytes32[] internal tree;      // the 2-leaf tree used by most tests
    bytes32[] internal bigTree;   // the 500-leaf tree used by the gas test

    event Claimed(uint256 index, address account, uint256 amount);
    event Swept(address indexed to, uint256 amount);

    // ─── OZ StandardMerkleTree, reimplemented for test fixtures ──────────────
    //
    // Mirrors @openzeppelin/merkle-tree's `makeMerkleTree`: a complete binary
    // tree laid out in one array, leaves stored from the END backwards, each
    // internal node the sorted-pair hash of its two children. Sorted pairs are
    // what OZ's on-chain MerkleProof.verify assumes, so a tree built any other
    // way would produce proofs that fail for reasons unrelated to the contract.

    function _leaf(uint256 index, address account, uint256 amount) internal pure returns (bytes32) {
        return keccak256(bytes.concat(keccak256(abi.encode(index, account, amount))));
    }

    function _hashPair(bytes32 a, bytes32 b) internal pure returns (bytes32) {
        return a < b ? keccak256(abi.encode(a, b)) : keccak256(abi.encode(b, a));
    }

    function _buildTree(bytes32[] memory leaves) internal pure returns (bytes32[] memory t) {
        uint256 n = leaves.length;
        t = new bytes32[](2 * n - 1);
        for (uint256 i = 0; i < n; i++) {
            t[t.length - 1 - i] = leaves[i];
        }
        // Internal nodes are indices 0..n-2, filled bottom-up.
        for (uint256 i = n - 1; i > 0; i--) {
            t[i - 1] = _hashPair(t[2 * (i - 1) + 1], t[2 * (i - 1) + 2]);
        }
    }

    function _getProof(bytes32[] memory t, uint256 leafIdx) internal pure returns (bytes32[] memory proof) {
        uint256 idx = t.length - 1 - leafIdx;
        bytes32[] memory scratch = new bytes32[](256);
        uint256 c = 0;
        while (idx > 0) {
            uint256 sibling = idx % 2 == 0 ? idx - 1 : idx + 1;
            scratch[c++] = t[sibling];
            idx = (idx - 1) / 2;
        }
        proof = new bytes32[](c);
        for (uint256 i = 0; i < c; i++) proof[i] = scratch[i];
    }

    function setUp() public {
        token = new MockERC20();

        bytes32[] memory leaves = new bytes32[](2);
        leaves[0] = _leaf(0, alice, ALICE_AMOUNT);
        leaves[1] = _leaf(1, bob, BOB_AMOUNT);
        tree = _buildTree(leaves);

        dist = new MerkleDistributor(address(token), tree[0], dist_NO_DEADLINE(), owner);
        token.mint(address(dist), TOTAL);
    }

    function dist_NO_DEADLINE() internal pure returns (uint256) {
        return type(uint256).max;
    }

    // ─── A. Happy path ───────────────────────────────────────────────────────

    function test_ClaimTransfersExactAmountAndEmits() public {
        bytes32[] memory proof = _getProof(tree, 0);

        vm.expectEmit(true, true, true, true);
        emit Claimed(0, alice, ALICE_AMOUNT);

        dist.claim(0, alice, ALICE_AMOUNT, proof);

        assertEq(token.balanceOf(alice), ALICE_AMOUNT, "alice balance");
        assertEq(token.balanceOf(address(dist)), BOB_AMOUNT, "distributor remainder");
        assertTrue(dist.isClaimed(0), "index 0 marked claimed");
        assertFalse(dist.isClaimed(1), "index 1 untouched");
    }

    /// 1 wei must claim exactly as well as 1000 tokens — no rounding anywhere.
    function test_ClaimOfOneWei() public {
        dist.claim(1, bob, BOB_AMOUNT, _getProof(tree, 1));
        assertEq(token.balanceOf(bob), 1, "bob got exactly 1 wei");
    }

    /**
     * Anyone may submit; the tokens still go to `account`.
     *
     * This is the property that lets a relayer pay gas for holders who have no
     * native ETH on a freshly launched chain — a large fraction of them, in
     * practice. Asserted rather than assumed, because a future "only the
     * recipient may claim" tightening would break that path silently.
     */
    function test_ThirdPartyCanSubmitClaimForSomeoneElse() public {
        vm.prank(relayer);
        dist.claim(0, alice, ALICE_AMOUNT, _getProof(tree, 0));

        assertEq(token.balanceOf(alice), ALICE_AMOUNT, "recipient credited");
        assertEq(token.balanceOf(relayer), 0, "submitter credited nothing");
    }

    // ─── A. Rejections ───────────────────────────────────────────────────────

    function test_DoubleClaimReverts() public {
        bytes32[] memory proof = _getProof(tree, 0);
        dist.claim(0, alice, ALICE_AMOUNT, proof);

        vm.expectRevert(MerkleDistributor.AlreadyClaimed.selector);
        dist.claim(0, alice, ALICE_AMOUNT, proof);
    }

    function test_WrongAmountReverts() public {
        vm.expectRevert(MerkleDistributor.InvalidProof.selector);
        dist.claim(0, alice, ALICE_AMOUNT + 1, _getProof(tree, 0));
    }

    function test_WrongAccountReverts() public {
        vm.expectRevert(MerkleDistributor.InvalidProof.selector);
        dist.claim(0, bob, ALICE_AMOUNT, _getProof(tree, 0));
    }

    function test_WrongIndexReverts() public {
        vm.expectRevert(MerkleDistributor.InvalidProof.selector);
        dist.claim(1, alice, ALICE_AMOUNT, _getProof(tree, 0));
    }

    function test_WrongProofReverts() public {
        vm.expectRevert(MerkleDistributor.InvalidProof.selector);
        dist.claim(0, alice, ALICE_AMOUNT, _getProof(tree, 1)); // bob's proof
    }

    function test_EmptyProofReverts() public {
        vm.expectRevert(MerkleDistributor.InvalidProof.selector);
        dist.claim(0, alice, ALICE_AMOUNT, new bytes32[](0));
    }

    /// An address absent from the tree cannot manufacture a claim.
    function test_NonRecipientReverts() public {
        vm.expectRevert(MerkleDistributor.InvalidProof.selector);
        dist.claim(2, address(0xBEEF), 1e18, _getProof(tree, 0));
    }

    function test_ConstructorRejectsZeroToken() public {
        vm.expectRevert(MerkleDistributor.ZeroAddress.selector);
        new MerkleDistributor(address(0), tree[0], type(uint256).max, owner);
    }

    // ─── A. Bitmap ───────────────────────────────────────────────────────────

    /**
     * The bitmap packs 256 indices per storage word, so indices 255 and 256 sit
     * in different words and index 0 shares a word with 255. An off-by-one in
     * `index >> 8` or `1 << (index & 0xff)` would either collide two holders
     * onto one bit — the second claimant silently blocked — or wrap. Checked at
     * the exact boundary rather than trusted.
     */
    function test_BitmapWordBoundary() public {
        uint256[3] memory idxs = [uint256(0), 255, 256];
        bytes32[] memory leaves = new bytes32[](3);
        for (uint256 i = 0; i < 3; i++) leaves[i] = _leaf(idxs[i], alice, 1e18);
        bytes32[] memory t = _buildTree(leaves);

        MerkleDistributor d = new MerkleDistributor(address(token), t[0], type(uint256).max, owner);
        token.mint(address(d), 3e18);

        for (uint256 i = 0; i < 3; i++) {
            assertFalse(d.isClaimed(idxs[i]), "not claimed yet");
        }
        d.claim(255, alice, 1e18, _getProof(t, 1));
        assertTrue(d.isClaimed(255), "255 claimed");
        assertFalse(d.isClaimed(0), "0 must not be affected by 255");
        assertFalse(d.isClaimed(256), "256 must not be affected by 255");

        d.claim(256, alice, 1e18, _getProof(t, 2));
        d.claim(0, alice, 1e18, _getProof(t, 0));
        assertEq(token.balanceOf(alice), 3e18, "all three paid");
    }

    // ─── A. Sweep ────────────────────────────────────────────────────────────

    function test_SweepBeforeDeadlineReverts() public {
        uint256 deadline = block.timestamp + 30 days;
        MerkleDistributor d = new MerkleDistributor(address(token), tree[0], deadline, owner);
        token.mint(address(d), TOTAL);

        vm.prank(owner);
        vm.expectRevert(MerkleDistributor.SweepBeforeDeadline.selector);
        d.sweep(owner);

        // One second early is still early.
        vm.warp(deadline - 1);
        vm.prank(owner);
        vm.expectRevert(MerkleDistributor.SweepBeforeDeadline.selector);
        d.sweep(owner);
    }

    function test_SweepAfterDeadlineMovesRemainder() public {
        uint256 deadline = block.timestamp + 30 days;
        MerkleDistributor d = new MerkleDistributor(address(token), tree[0], deadline, owner);
        token.mint(address(d), TOTAL);

        // Alice claims; only Bob's 1 wei should be left to sweep.
        d.claim(0, alice, ALICE_AMOUNT, _getProof(tree, 0));

        vm.warp(deadline);
        vm.expectEmit(true, true, true, true);
        emit Swept(owner, BOB_AMOUNT);
        vm.prank(owner);
        d.sweep(owner);

        assertEq(token.balanceOf(owner), BOB_AMOUNT, "swept remainder");
        assertEq(token.balanceOf(address(d)), 0, "distributor drained");
    }

    function test_SweepNonOwnerReverts() public {
        uint256 deadline = block.timestamp + 1 days;
        MerkleDistributor d = new MerkleDistributor(address(token), tree[0], deadline, owner);
        token.mint(address(d), TOTAL);
        vm.warp(deadline + 1);

        vm.prank(alice);
        vm.expectRevert(abi.encodeWithSelector(Ownable.OwnableUnauthorizedAccount.selector, alice));
        d.sweep(alice);
    }

    function test_SweepToZeroAddressReverts() public {
        uint256 deadline = block.timestamp + 1 days;
        MerkleDistributor d = new MerkleDistributor(address(token), tree[0], deadline, owner);
        vm.warp(deadline + 1);

        vm.prank(owner);
        vm.expectRevert(MerkleDistributor.ZeroAddress.selector);
        d.sweep(address(0));
    }

    /**
     * With the NO_DEADLINE sentinel, sweep is unreachable — not "hard to
     * reach", unreachable, because block.timestamp cannot attain 2^256-1.
     * This is the default the runbook deploys with, so it is asserted at a
     * timestamp far past any plausible chain lifetime.
     */
    function test_NoDeadlineSentinelMakesSweepUnreachable() public {
        assertEq(dist.claimDeadline(), type(uint256).max, "sentinel stored");

        vm.warp(type(uint64).max); // ~year 584 billion
        vm.prank(owner);
        vm.expectRevert(MerkleDistributor.SweepBeforeDeadline.selector);
        dist.sweep(owner);
    }

    /// Claiming must keep working after a sweep window opens but before it is used.
    function test_ClaimStillWorksAfterDeadlinePasses() public {
        uint256 deadline = block.timestamp + 1 days;
        MerkleDistributor d = new MerkleDistributor(address(token), tree[0], deadline, owner);
        token.mint(address(d), TOTAL);

        vm.warp(deadline + 365 days);
        d.claim(0, alice, ALICE_AMOUNT, _getProof(tree, 0));
        assertEq(token.balanceOf(alice), ALICE_AMOUNT, "late claim still honoured");
    }

    // ─── B. Cross-implementation: the TypeScript builder's real output ───────

    /**
     * Root and proofs below were produced by
     *   npm run merkle:build -- scripts/fixtures/claim-allocations.fixture.csv
     * and copied verbatim. No Solidity produced them.
     *
     * Two rows are checked: the largest-index row (9) and the 1-wei row (3),
     * because index and amount are the two leaf fields most likely to be
     * encoded inconsistently between the two implementations.
     */
    function test_ClaimsAgainstRootFromTypeScriptBuilder() public {
        bytes32 tsRoot = 0x21c91829a215a6d27e81891ecda7d8aa056330b5aeacb0a6912f282cc912890a;

        address holder = 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266;
        uint256 holderAmount = 32_505_310_000_000_000_000_000;
        bytes32[] memory holderProof = new bytes32[](4);
        holderProof[0] = 0x041e7926123ddd8cb5dbe0baa15bce734f00fcbb9da2105aa626fabb75953458;
        holderProof[1] = 0x67753bcb53ab9f0bbae13b2cc6fd357782e17c959f1897471e3a1785e451b737;
        holderProof[2] = 0xb1576a15468c84282e80136fe416b5559fdecc5b4986c52af735c8bb172eb693;
        holderProof[3] = 0x2bac5f6d0912cfe6aba1ca08baa7aec172e1bca37e2492b2e7b1082c88e384ba;

        address dustHolder = 0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC;
        bytes32[] memory dustProof = new bytes32[](4);
        dustProof[0] = 0x3958dd528551d5827c31a03418f311e689164007bf1ed8f444b581cc058bb27e;
        dustProof[1] = 0x5197dfff91fc8d96d4eebb5540ea1b265e264125284c7b150de0e1f062228e3f;
        dustProof[2] = 0xb1576a15468c84282e80136fe416b5559fdecc5b4986c52af735c8bb172eb693;
        dustProof[3] = 0x2bac5f6d0912cfe6aba1ca08baa7aec172e1bca37e2492b2e7b1082c88e384ba;

        MerkleDistributor d = new MerkleDistributor(address(token), tsRoot, type(uint256).max, owner);
        token.mint(address(d), holderAmount + 1);

        d.claim(9, holder, holderAmount, holderProof);
        assertEq(token.balanceOf(holder), holderAmount, "TS-proof claim credited");

        d.claim(3, dustHolder, 1, dustProof);
        assertEq(token.balanceOf(dustHolder), 1, "TS-proof 1-wei claim credited");

        // And the same proofs must still be rejected when tampered with.
        vm.expectRevert(MerkleDistributor.InvalidProof.selector);
        d.claim(8, holder, holderAmount, holderProof);
    }

    // ─── Gas ─────────────────────────────────────────────────────────────────

    /**
     * Gas for one claim in a ~500-leaf tree (proof depth 9).
     *
     * Two claims are measured because they cost materially different amounts:
     * the first claim in a 256-index bitmap word pays ~20k to allocate that
     * storage slot, every later claim in the same word pays ~5k to update it.
     * Quoting only the cheap one would understate what most holders actually
     * pay, and quoting only the expensive one would hide the packing benefit
     * the bitmap exists for.
     *
     * The ceiling is a regression guard, not a target — it should only ever
     * move in a commit that explains why.
     */
    function test_GasSnapshot500Leaves() public {
        uint256 n = 500;
        bytes32[] memory leaves = new bytes32[](n);
        address[] memory holders = new address[](n);
        for (uint256 i = 0; i < n; i++) {
            holders[i] = address(uint160(0x1000 + i));
            leaves[i] = _leaf(i, holders[i], (i + 1) * 1e18);
        }
        bigTree = _buildTree(leaves);

        MerkleDistributor d = new MerkleDistributor(address(token), bigTree[0], type(uint256).max, owner);
        token.mint(address(d), 200_000_000e18);

        bytes32[] memory p0 = _getProof(bigTree, 0);
        assertEq(p0.length, 9, "proof depth for 500 leaves");

        uint256 g0 = gasleft();
        d.claim(0, holders[0], 1e18, p0);
        uint256 coldGas = g0 - gasleft();

        bytes32[] memory p1 = _getProof(bigTree, 1);
        uint256 g1 = gasleft();
        d.claim(1, holders[1], 2e18, p1);
        uint256 warmGas = g1 - gasleft();

        console.log("claim gas, 500-leaf tree (proof depth 9):");
        console.log("  cold bitmap word (first claim in a group of 256):", coldGas);
        console.log("  warm bitmap word (the other 255):               ", warmGas);

        assertLt(coldGas, 120_000, "cold claim gas regressed");
        assertLt(warmGas, 100_000, "warm claim gas regressed");
        assertLt(warmGas, coldGas, "bitmap packing should make later claims cheaper");
    }
}
