// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import { IERC20 } from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import { SafeERC20 } from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import { MerkleProof } from "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol";
import { Ownable } from "@openzeppelin/contracts/access/Ownable.sol";

/**
 * MerkleDistributor — the $NEW claim contract for the $BLUEAGENT migration.
 *
 * Ported from Uniswap's merkle-distributor (github.com/Uniswap/merkle-distributor),
 * the pattern every major airdrop since 2020 has used: publish one 32-byte root,
 * let each recipient prove their own leaf, mark it claimed in a bitmap.
 *
 * ─── What this contract deliberately CANNOT do ──────────────────────────────
 *
 * There is no pause, no root update, no owner mint, no allocation edit, no
 * upgrade path, and no way for the owner to move a single token before
 * `claimDeadline`. That is the entire security argument, and it is worth being
 * explicit about why each absence is load-bearing:
 *
 *   • NO setRoot. A mutable root means the allocation table published to
 *     holders and the one the contract pays against are two different things
 *     that merely happen to agree today. If the root is wrong we deploy a NEW
 *     contract and publish the new address — the old one keeps whatever it
 *     holds until the deadline. Allocations are never edited in place, because
 *     "we fixed your allocation" and "we changed your allocation" are the same
 *     transaction and nobody outside can tell them apart.
 *
 *   • NO pause. A pause on a claim contract is a freeze on other people's
 *     tokens. The failure it is supposed to protect against — a bad root —
 *     is not fixable by pausing anyway (see above), so it would buy nothing
 *     and cost the one property claimants actually need: that the contract
 *     cannot be turned off after they were told to rely on it.
 *
 *   • `sweep` is the ONLY owner power, and it is time-locked behind
 *     `claimDeadline`, which is fixed at construction and cannot be moved.
 *     Deploying with the `NO_DEADLINE` sentinel makes sweep permanently
 *     unreachable, which is the default posture: unclaimed tokens stay
 *     claimable forever unless a deadline was committed to UP FRONT, in
 *     public, before anyone claimed. A deadline that can be introduced later
 *     is not a deadline, it is a withdrawal.
 *
 * ─── Leaf encoding: OpenZeppelin StandardMerkleTree, NOT Uniswap's ──────────
 *
 * The 2020 Uniswap original hashes leaves as
 *   keccak256(abi.encodePacked(index, account, amount))
 * This contract instead uses OpenZeppelin's StandardMerkleTree encoding
 *   keccak256(bytes.concat(keccak256(abi.encode(index, account, amount))))
 * because the proofs are generated by the openzeppelin/merkle-tree npm
 * package (the leading "at" sign is omitted throughout this comment because
 * solc would read it as a natspec tag), and the two
 * schemes are NOT interchangeable — mixing them produces a contract where
 * every single proof fails verification. Picking one and stating it here is
 * the whole point of this paragraph.
 *
 * OZ's encoding is also the stronger of the two, for two independent reasons:
 *
 *   1. DOUBLE HASHING. With single-hashed leaves, a leaf preimage is 84 bytes
 *      (32 + 20 + 32 under encodePacked) while an internal node preimage is 64.
 *      Those lengths differ here, so the classic second-preimage attack does
 *      not apply to this particular layout — but it applies to any layout whose
 *      leaf happens to be 64 bytes, and relying on "our field widths happen to
 *      not sum to 64" is a property that a future schema change silently
 *      breaks. Hashing the leaf twice makes the domain separation structural
 *      instead of coincidental.
 *
 *   2. abi.encode, NOT abi.encodePacked. Packed encoding concatenates without
 *      padding, so adjacent dynamic fields can be re-split ambiguously. All
 *      three fields here are fixed-width, so again there is no live ambiguity —
 *      and again, the safety comes from the field types rather than from the
 *      hashing scheme, which is the wrong place for it to come from.
 *
 * `MerkleProof.verify` hashes each pair in sorted order, which is exactly what
 * StandardMerkleTree does when it builds the tree, so proofs from
 * `scripts/build-merkle.ts` verify here unmodified.
 *
 * `contracts/test/MerkleDistributor.t.sol` asserts this compatibility against
 * a root generated by the real TypeScript script rather than by a Solidity
 * reimplementation of it — a Solidity-side tree would only prove the contract
 * agrees with itself.
 */
contract MerkleDistributor is Ownable {
    using SafeERC20 for IERC20;

    /**
     * Sentinel for "there is no deadline" — sweep can never be called, because
     * `block.timestamp` cannot reach 2^256-1. This is the DEFAULT the runbook
     * deploys with; a real deadline is opt-in and must be decided before the
     * root is published, never after.
     */
    uint256 public constant NO_DEADLINE = type(uint256).max;

    /// The token being distributed. Immutable — the contract pays one asset.
    IERC20 public immutable token;

    /// The allocation table, as a single 32-byte commitment. Final by design.
    bytes32 public immutable merkleRoot;

    /// Unix seconds. Before this, `sweep` reverts. `NO_DEADLINE` = never.
    uint256 public immutable claimDeadline;

    /**
     * One bit per allocation index. Word `i >> 8`, bit `i & 0xff`.
     *
     * A bitmap rather than `mapping(uint256 => bool)` because 256 claims share
     * a storage slot: the first claim in a word pays for the slot and the next
     * 255 pay ~5k gas instead of ~20k. On a table of thousands of holders that
     * is the difference between a claim costing a few cents and costing real
     * money on a chain where the recipient may hold very little native ETH.
     */
    mapping(uint256 => uint256) private claimedBitMap;

    event Claimed(uint256 index, address account, uint256 amount);
    event Swept(address indexed to, uint256 amount);

    error AlreadyClaimed();
    error InvalidProof();
    error SweepBeforeDeadline();
    error ZeroAddress();

    /**
     * @param token_         ERC-20 being distributed ($NEW on Robinhood Chain).
     * @param merkleRoot_    Root of the published allocation table. FINAL.
     * @param claimDeadline_ Unix seconds after which the owner may sweep the
     *                       remainder. Pass `NO_DEADLINE` (type(uint256).max)
     *                       for "unclaimed tokens stay claimable forever".
     * @param initialOwner_  Holder of the sweep power. Passed explicitly rather
     *                       than defaulting to `msg.sender` so that deploying
     *                       from a throwaway hot key does not silently hand
     *                       that key the only privileged role on the contract.
     *
     * NOTE: the deployer does NOT need to be the owner, and the owner needs no
     * tokens — funding is a plain ERC-20 transfer to this address, done after
     * deployment (see claim-data/RUNBOOK.md).
     */
    constructor(address token_, bytes32 merkleRoot_, uint256 claimDeadline_, address initialOwner_)
        Ownable(initialOwner_)
    {
        if (token_ == address(0)) revert ZeroAddress();
        token = IERC20(token_);
        merkleRoot = merkleRoot_;
        claimDeadline = claimDeadline_;
    }

    /// @return True once index `index` has been claimed.
    function isClaimed(uint256 index) public view returns (bool) {
        uint256 word = claimedBitMap[index >> 8];
        return word & (1 << (index & 0xff)) != 0;
    }

    function _setClaimed(uint256 index) private {
        claimedBitMap[index >> 8] |= (1 << (index & 0xff));
    }

    /**
     * Claim `amount` for `account`, proving membership in the published table.
     *
     * Deliberately callable by ANYONE, not just `account` — the tokens always
     * go to `account`, so a third party submitting the transaction can only
     * spend their own gas on someone else's behalf. That keeps the door open
     * for a relayer to cover claims for holders who have no ETH on the
     * destination chain, which on a fresh chain is a real fraction of them.
     *
     * Effects (bitmap) precede the interaction (transfer), so a token with a
     * transfer hook cannot re-enter and claim the same index twice.
     */
    function claim(uint256 index, address account, uint256 amount, bytes32[] calldata merkleProof) external {
        if (isClaimed(index)) revert AlreadyClaimed();

        // OZ StandardMerkleTree leaf: keccak256(keccak256(abi.encode(...))).
        // See the contract-level comment for why this is not encodePacked.
        bytes32 leaf = keccak256(bytes.concat(keccak256(abi.encode(index, account, amount))));
        if (!MerkleProof.verify(merkleProof, merkleRoot, leaf)) revert InvalidProof();

        _setClaimed(index);
        token.safeTransfer(account, amount);

        emit Claimed(index, account, amount);
    }

    /**
     * Move whatever is left to `to`, only after `claimDeadline`.
     *
     * Sweeps the full balance rather than an operator-supplied amount: the
     * decision this function exists to serve is "the window is over", and a
     * partial sweep is that decision applied to some claimants and not others.
     * Emitting the amount keeps it auditable either way.
     */
    function sweep(address to) external onlyOwner {
        if (block.timestamp < claimDeadline) revert SweepBeforeDeadline();
        if (to == address(0)) revert ZeroAddress();

        uint256 remaining = token.balanceOf(address(this));
        token.safeTransfer(to, remaining);

        emit Swept(to, remaining);
    }
}
