// ─── Agent Tool types & seeded data ──────────────────────────────────────────

export type AgentToolInput = {
  key: string;
  label: string;
  placeholder: string;
  required?: boolean;
};

export type CompositeSkill = {
  agentType: "aeon" | "blue" | "miroshark";
  skillId?: string;
  skillFiles?: string[];
  label: string;
};

const X402_BASE = "https://blueagent.dev/api/x402";

// Blue Hub treasury — default builder address for Blue Agent first-party tools.
// Builder-submitted tools (Hub v2 Phase 3) will set this to the builder's own wallet.
export const BLUE_TREASURY = "0xb058a1e305d9c720aa5b1bf42b6f2f6294b03b5f" as const;

export type AgentTool = {
  id: string;
  name: string;
  description: string;
  agentHandle: string;
  agentName: string;
  agentType: "aeon" | "blue" | "miroshark" | "composite";
  category: string;
  skillId?: string;
  skillFiles?: string[];
  inputs: AgentToolInput[];
  isComposite: boolean;
  compositeSkills?: CompositeSkill[];
  featured?: boolean;
  // x402 payment
  price?: string;          // e.g. "$0.20"
  priceUSDC?: number;      // in USDC units (6 decimals), e.g. 200000 = $0.20
  x402Url?: string;        // full x402 endpoint URL — if set, payment is required
  x402Body?: (values: Record<string, string>) => Record<string, unknown>; // maps hub inputs → x402 body
  // v2 marketplace metadata — defaults applied via withV2Defaults() at bottom of file
  verified?:       boolean;          // Blue Agent reviewed; default true for first-party
  aiReady?:        boolean;          // Returns structured JSON; default true
  builderAddress?: `0x${string}`;    // Revenue recipient; default BLUE_TREASURY
  releasedAt?:    number;            // Unix ms — drives "Newest" sort; default 2024-06-01
};

// ─── All 64 tools ─────────────────────────────────────────────────────────────

const AGENT_TOOLS_RAW: AgentTool[] = [

  // ── Intelligence ────────────────────────────────────────────────────────────

  {
    id: "token-pick-signal",
    name: "Token Pick Signal",
    description: "AI consensus on the highest-conviction asymmetric token setup on Base right now.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "intelligence",
    skillId: "token-pick",
    inputs: [
      { key: "context", label: "Market context (optional)", placeholder: "e.g. low-cap DeFi, AI agent tokens, memecoins" },
    ],
    isComposite: true,
    featured: true,
    price: "$0.20",
    priceUSDC: 200000,
    x402Url: `${X402_BASE}/token-pick-signal`,
    x402Body: (v) => ({ chain: "base", context: v.context ?? "" }),
  },
  {
    id: "narrative-position",
    name: "Narrative Position",
    description: "Which narratives are building vs peaking on CT — and where to position.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "intelligence",
    skillId: "narrative-tracker",
    inputs: [
      { key: "focus", label: "Narrative focus (optional)", placeholder: "e.g. AI agents, RWA, Base DeFi" },
    ],
    isComposite: true,
    featured: true,
    price: "$0.15",
    priceUSDC: 150000,
    x402Url: `${X402_BASE}/narrative-position`,
    x402Body: (v) => ({ topic: v.focus ?? "", focus: v.focus ?? "" }),
  },
  {
    id: "ecosystem-digest",
    name: "Ecosystem Digest",
    description: "Weekly Base ecosystem intelligence: top builders, protocols, and narratives.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "intelligence",
    skillId: "digest",
    inputs: [
      { key: "focus", label: "Focus area (optional)", placeholder: "e.g. DeFi protocols, AI agents, gaming" },
    ],
    isComposite: true,
    price: "$0.20",
    priceUSDC: 200000,
    x402Url: `${X402_BASE}/ecosystem-digest`,
    x402Body: (v) => ({ focus: v.focus ?? "" }),
  },
  {
    id: "market-fit",
    name: "Market Fit Validator",
    description: "Score your product's market fit with swarm intelligence across three personas.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "intelligence",
    inputs: [
      { key: "description", label: "Product description", placeholder: "What you're building, who it's for, and what problem it solves", required: true },
      { key: "stage", label: "Stage", placeholder: "e.g. idea, MVP, live product" },
    ],
    isComposite: true,
    featured: true,
    price: "$0.25",
    priceUSDC: 250000,
    x402Url: `${X402_BASE}/market-fit`,
    x402Body: (v) => ({ description: v.description ?? "", name: "", stage: v.stage ?? "idea" }),
  },
  {
    id: "token-launch-readiness",
    name: "Token Launch Readiness",
    description: "Go/no-go signal on whether your project is ready to launch a token.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "intelligence",
    inputs: [
      { key: "name", label: "Project / token name", placeholder: "e.g. $MYTOKEN or your project name", required: true },
      { key: "description", label: "Project description + traction", placeholder: "What the project does, current metrics, community size, any live product" },
    ],
    isComposite: true,
    price: "$0.30",
    priceUSDC: 300000,
    x402Url: `${X402_BASE}/token-launch-readiness`,
    x402Body: (v) => ({ name: v.name ?? "", project: v.name ?? "", description: v.description ?? "" }),
  },

  // ── Builder ─────────────────────────────────────────────────────────────────

  {
    id: "roadmap-validator",
    name: "Roadmap Validator",
    description: "Validate your roadmap against market timing, execution risk, and narrative fit.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "project", label: "Project name", placeholder: "Your project name", required: true },
      { key: "roadmap", label: "Roadmap milestones", placeholder: "Q1: X, Q2: Y, Q3: Z — be specific about what you plan to ship", required: true },
    ],
    isComposite: true,
    price: "$0.25",
    priceUSDC: 250000,
    x402Url: `${X402_BASE}/roadmap-validator`,
    x402Body: (v) => ({ project: v.project ?? "", roadmap: v.roadmap ?? "" }),
  },
  {
    id: "competitor-scan",
    name: "Competitor Scan",
    description: "Identify direct/indirect competitors and surface your defensible edge.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "project", label: "Your project", placeholder: "What you build and your main value prop", required: true },
      { key: "category", label: "Category", placeholder: "e.g. DeFi lending, AI agent, NFT marketplace" },
    ],
    isComposite: true,
    price: "$0.20",
    priceUSDC: 200000,
    x402Url: `${X402_BASE}/competitor-scan`,
    x402Body: (v) => ({ project: v.project ?? "", description: v.project ?? "", competitors: v.category ?? "" }),
  },
  {
    id: "pitch-intelligence",
    name: "Pitch Intelligence",
    description: "Transform your deck into investor-grade pitch intelligence with narrative scoring.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "project", label: "Project", placeholder: "Project name", required: true },
      { key: "description", label: "Pitch summary", placeholder: "Problem you solve, your solution, traction so far, and funding ask", required: true },
    ],
    isComposite: true,
    price: "$0.30",
    priceUSDC: 300000,
    x402Url: `${X402_BASE}/pitch-intelligence`,
    x402Body: (v) => ({ project: v.project ?? "", description: v.description ?? "" }),
  },
  {
    id: "fundraise-timing",
    name: "Fundraise Timing",
    description: "Is now the right time to raise? Market conditions, stage readiness, investor appetite.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "project", label: "Project", placeholder: "What you build", required: true },
      { key: "stage", label: "Stage & metrics", placeholder: "e.g. pre-seed, current MRR, user count, what you've shipped" },
    ],
    isComposite: true,
    price: "$0.20",
    priceUSDC: 200000,
    x402Url: `${X402_BASE}/fundraise-timing`,
    x402Body: (v) => ({ project: v.project ?? "", stage: v.stage ?? "" }),
  },
  {
    id: "gtm-brief",
    name: "GTM Brief",
    description: "Go-to-market playbook: channels, timing, messaging, and early adopter strategy.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "project", label: "Project name", placeholder: "Your project name", required: true },
      { key: "description", label: "What you're launching", placeholder: "Product description and core value prop", required: true },
      { key: "target", label: "Target audience", placeholder: "Who are your first 100 users?" },
    ],
    isComposite: true,
    price: "$0.25",
    priceUSDC: 250000,
    x402Url: `${X402_BASE}/gtm-brief`,
    x402Body: (v) => ({ project: v.project ?? "", description: v.description ?? "", target: v.target ?? "" }),
  },
  {
    id: "stack-recommender",
    name: "Stack Recommender",
    description: "Optimal tech stack for Base builders — infra, tooling, protocols, integrations.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "project_type", label: "Project type", placeholder: "e.g. DeFi protocol, AI agent, consumer app, NFT marketplace", required: true },
      { key: "constraints", label: "Constraints", placeholder: "e.g. solo dev, 2-week timeline, TypeScript only" },
    ],
    isComposite: true,
    price: "$0.20",
    priceUSDC: 200000,
    x402Url: `${X402_BASE}/stack-recommender`,
    x402Body: (v) => ({ project: v.project_type ?? "", description: v.project_type ?? "", team_size: "1", timeline: v.constraints ?? "" }),
  },
  {
    id: "investor-memo",
    name: "Investor Memo",
    description: "Full investor memo: thesis, market, moat, risks, and ask — ready to send.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "project", label: "Project name", placeholder: "Your project name", required: true },
      { key: "description", label: "Description + traction", placeholder: "What you do, current metrics, revenue, community — use real numbers", required: true },
      { key: "ask", label: "Raise ask", placeholder: "e.g. $500k pre-seed, $2M seed" },
    ],
    isComposite: true,
    featured: true,
    price: "$0.35",
    priceUSDC: 350000,
    x402Url: `${X402_BASE}/investor-memo`,
    x402Body: (v) => ({ project: v.project ?? "", description: v.description ?? "", ask: v.ask ?? "", stage: "pre-seed", traction: v.description ?? "" }),
  },
  {
    id: "token-distribution-plan",
    name: "Token Distribution Plan",
    description: "Token allocation framework: team, community, investors, treasury, liquidity.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "token", label: "Token / project name", placeholder: "Your token ticker or project name", required: true },
      { key: "total_supply", label: "Total supply", placeholder: "e.g. 1,000,000,000" },
      { key: "description", label: "Stage & context", placeholder: "pre-launch or post-TGE? community focus or VC-backed?" },
    ],
    isComposite: true,
    price: "$0.30",
    priceUSDC: 300000,
    x402Url: `${X402_BASE}/token-distribution-plan`,
    x402Body: (v) => ({ token: v.token ?? "", ticker: v.token ?? "", total_supply: v.total_supply ?? "1000000000", description: v.description ?? "" }),
  },
  {
    id: "agent-performance",
    name: "Agent Performance",
    description: "Benchmark your AI agent's revenue, engagement, and retention metrics.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "handle", label: "Agent X/Twitter handle", placeholder: "@yourhandle", required: true },
      { key: "repo", label: "GitHub repo (optional)", placeholder: "user/repo" },
    ],
    isComposite: true,
    price: "$0.25",
    priceUSDC: 250000,
    x402Url: `${X402_BASE}/agent-performance`,
    x402Body: (v) => ({ handle: v.handle ?? "", repo: v.repo ?? "" }),
  },
  {
    id: "agent-collab-match",
    name: "Agent Collab Match",
    description: "Find agents that complement your tool and surface collab opportunities.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "agent_a", label: "Your agent", placeholder: "Your agent name and what it does", required: true },
      { key: "agent_b", label: "Target agent", placeholder: "Agent name to evaluate collab with, or 'any'", required: true },
      { key: "collab_goal", label: "Collab goal", placeholder: "e.g. joint tool, cross-promote, revenue share" },
    ],
    isComposite: true,
    price: "$0.20",
    priceUSDC: 200000,
    x402Url: `${X402_BASE}/agent-collab-match`,
    x402Body: (v) => ({ agent_a: v.agent_a ?? "", agent_b: v.agent_b ?? "", collab_goal: v.collab_goal ?? "" }),
  },
  {
    id: "repo-health",
    name: "Repo Health",
    description: "Audit your GitHub repo health: code quality, docs, CI, contributor signals.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "repo", label: "GitHub repo", placeholder: "user/repo or full GitHub URL", required: true },
    ],
    isComposite: true,
    price: "$0.20",
    priceUSDC: 200000,
    x402Url: `${X402_BASE}/repo-health`,
    x402Body: (v) => ({ repo: v.repo ?? "", description: v.repo ?? "" }),
  },
  {
    id: "community-sentiment",
    name: "Community Sentiment",
    description: "Real-time sentiment analysis across your community channels.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "project", label: "Project / token", placeholder: "Project name or token ticker", required: true },
      { key: "channels", label: "Channels", placeholder: "e.g. Twitter @handle, Telegram link, Discord" },
    ],
    isComposite: true,
    price: "$0.20",
    priceUSDC: 200000,
    x402Url: `${X402_BASE}/community-sentiment`,
    x402Body: (v) => ({ project: v.project ?? "", description: v.channels ?? "" }),
  },
  {
    id: "defi-opportunity",
    name: "DeFi Opportunity",
    description: "Scan Base DeFi for emerging yield, liquidity, and protocol opportunities.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "focus", label: "Focus (optional)", placeholder: "e.g. stablecoin yield, LP, lending, new protocols" },
      { key: "risk_tolerance", label: "Risk tolerance", placeholder: "low / medium / high" },
    ],
    isComposite: true,
    price: "$0.25",
    priceUSDC: 250000,
    x402Url: `${X402_BASE}/defi-opportunity`,
    x402Body: (v) => ({ strategy: v.focus ?? "yield farming", risk_tolerance: v.risk_tolerance ?? "medium" }),
  },
  {
    id: "builder-deep-dd",
    name: "Builder Deep DD",
    description: "Full due diligence on a Base builder: onchain activity, shipped products, credibility.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "target", label: "Builder handle or address", placeholder: "@twitterhandle or 0x… wallet address", required: true },
    ],
    isComposite: true,
    price: "$0.35",
    priceUSDC: 350000,
    x402Url: `${X402_BASE}/builder-deep-dd`,
    x402Body: (v) => ({ target: v.target ?? "", type: "builder" }),
  },
  {
    id: "launch-simulator",
    name: "Launch Simulator",
    description: "Simulate your token launch with 3-agent consensus: Blue strategy + Aeon market + MiroShark crowd.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "token_name", label: "Token name", placeholder: "e.g. $MYTOKEN", required: true },
      { key: "launch_price", label: "Launch price (USD)", placeholder: "e.g. 0.001", required: true },
      { key: "total_supply", label: "Total supply", placeholder: "e.g. 1000000000" },
      { key: "liquidity", label: "Initial liquidity (USD)", placeholder: "e.g. 50000" },
      { key: "tier", label: "Analysis tier", placeholder: "standard / deep / ultra" },
    ],
    isComposite: true,
    featured: true,
    price: "$0.50",
    priceUSDC: 500000,
    x402Url: `${X402_BASE}/token-launch-readiness`,
    x402Body: (v) => ({
      name: v.token_name ?? "",
      project: v.token_name ?? "",
      ticker: v.token_name ?? "",
      description: `Launch price: $${v.launch_price ?? "0"}, supply: ${v.total_supply ?? "1B"}, liquidity: $${v.liquidity ?? "50k"}`,
      traction: v.tier ?? "standard",
    }),
  },

  // ── Trading & Alpha ──────────────────────────────────────────────────────────

  {
    id: "whale-copy-signal",
    name: "Whale Copy Signal",
    description: "Track and copy high-alpha whale wallets on Base — entry, size, and timing.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "trading",
    inputs: [
      { key: "wallet", label: "Whale wallet (optional)", placeholder: "0x… leave blank to scan top Base whales" },
      { key: "token", label: "Token to watch (optional)", placeholder: "e.g. WETH, USDC, or a specific token ticker" },
    ],
    isComposite: true,
    price: "$0.25",
    priceUSDC: 250000,
    x402Url: `${X402_BASE}/whale-copy-signal`,
    x402Body: (v) => ({ wallet: v.wallet ?? "", token: v.token ?? "" }),
  },
  {
    id: "token-momentum-scanner",
    name: "Token Momentum Scanner",
    description: "Real-time momentum scan for Base tokens — breakouts, volume spikes, narrative alignment.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "trading",
    inputs: [
      { key: "timeframe", label: "Timeframe", placeholder: "e.g. 1h, 4h, 24h" },
      { key: "filter", label: "Filter", placeholder: "e.g. min $50k volume, specific narrative, mcap range" },
    ],
    isComposite: true,
    price: "$0.20",
    priceUSDC: 200000,
    x402Url: `${X402_BASE}/token-momentum-scanner`,
    x402Body: (v) => ({ chain: "base", context: `${v.timeframe ?? ""} ${v.filter ?? ""}`.trim() }),
  },
  {
    id: "portfolio-rebalancer",
    name: "Portfolio Rebalancer",
    description: "AI-driven portfolio rebalancing plan based on current Base market conditions.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "trading",
    inputs: [
      { key: "holdings", label: "Current portfolio", placeholder: "e.g. 50% ETH, 30% USDC, 20% altcoins — use real %", required: true },
      { key: "goal", label: "Goal", placeholder: "e.g. reduce risk, maximize yield, increase stablecoin exposure" },
    ],
    isComposite: true,
    price: "$0.25",
    priceUSDC: 250000,
    x402Url: `${X402_BASE}/portfolio-rebalancer`,
    x402Body: (v) => ({ holdings: v.holdings ?? "", risk_profile: "medium", goal: v.goal ?? "" }),
  },

  // ── Content ─────────────────────────────────────────────────────────────────

  {
    id: "thread-intelligence",
    name: "Thread Intelligence",
    description: "Turn your alpha or project update into a high-engagement X thread.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "content",
    inputs: [
      { key: "topic", label: "Thread topic", placeholder: "What do you want to write about?", required: true },
      { key: "angle", label: "Angle", placeholder: "e.g. alpha drop, project update, educational, hot take" },
    ],
    isComposite: true,
    price: "$0.20",
    priceUSDC: 200000,
    x402Url: `${X402_BASE}/thread-intelligence`,
    x402Body: (v) => ({ topic: v.topic ?? "", audience: "Base builders", goal: v.angle ?? "" }),
  },
  {
    id: "builder-brand-score",
    name: "Builder Brand Score",
    description: "Score your personal brand as a Base builder and get a growth playbook.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "content",
    inputs: [
      { key: "handle", label: "X / Twitter handle", placeholder: "@yourhandle", required: true },
      { key: "focus", label: "What you build", placeholder: "e.g. DeFi tools, AI agents, consumer apps" },
    ],
    isComposite: true,
    price: "$0.25",
    priceUSDC: 250000,
    x402Url: `${X402_BASE}/builder-brand-score`,
    x402Body: (v) => ({ builder: v.handle ?? "", handle: v.handle ?? "", project: v.focus ?? "" }),
  },
  {
    id: "community-growth-playbook",
    name: "Community Growth Playbook",
    description: "Proven growth tactics for Base builder communities — from 0 to 1000 members.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "content",
    inputs: [
      { key: "project", label: "Project name", placeholder: "Your project name", required: true },
      { key: "current_size", label: "Current community size", placeholder: "e.g. 50 Telegram members, 200 Twitter followers" },
    ],
    isComposite: true,
    price: "$0.25",
    priceUSDC: 250000,
    x402Url: `${X402_BASE}/community-growth-playbook`,
    x402Body: (v) => ({ project: v.project ?? "", current_size: v.current_size ?? "0", goal: "1000 active members" }),
  },

  // ── Agent Economy ────────────────────────────────────────────────────────────

  {
    id: "agent-revenue-optimizer",
    name: "Agent Revenue Optimizer",
    description: "Maximize your agent's x402 revenue: pricing, bundling, and distribution strategy.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "agent-economy",
    inputs: [
      { key: "agent", label: "Agent name", placeholder: "Your agent name", required: true },
      { key: "description", label: "Current tools / services", placeholder: "List your tools and current prices" },
      { key: "current_revenue", label: "Current revenue", placeholder: "e.g. $50/month — use real number for accurate output" },
    ],
    isComposite: true,
    price: "$0.30",
    priceUSDC: 300000,
    x402Url: `${X402_BASE}/agent-revenue-optimizer`,
    x402Body: (v) => ({ agent: v.agent ?? "", description: v.description ?? "", current_revenue: v.current_revenue ?? "0", model: "pay-per-use" }),
  },
  {
    id: "agent-token-strategy",
    name: "Agent Token Strategy",
    description: "Design your agent token: utility, distribution, tokenomics, and launch strategy.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "agent-economy",
    inputs: [
      { key: "agent", label: "Agent name", placeholder: "Your agent name", required: true },
      { key: "description", label: "Token use case", placeholder: "e.g. governance, access gating, rewards, revenue share" },
    ],
    isComposite: true,
    price: "$0.30",
    priceUSDC: 300000,
    x402Url: `${X402_BASE}/agent-token-strategy`,
    x402Body: (v) => ({ agent: v.agent ?? "", description: v.description ?? "", token_name: `${v.agent ?? "AGENT"}TOKEN` }),
  },
  {
    id: "multi-agent-workflow",
    name: "Multi-Agent Workflow",
    description: "Design an automated workflow combining multiple agents for complex tasks.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "agent-economy",
    inputs: [
      { key: "goal", label: "Workflow goal", placeholder: "What should this workflow accomplish end-to-end?", required: true },
      { key: "agents", label: "Agents to use (optional)", placeholder: "e.g. Blue Agent, Aeon, MiroShark, or your own" },
    ],
    isComposite: true,
    price: "$0.25",
    priceUSDC: 250000,
    x402Url: `${X402_BASE}/multi-agent-workflow`,
    x402Body: (v) => ({ goal: v.goal ?? "", agents: v.agents ?? "Blue Agent, Aeon, MiroShark" }),
  },

  // ── Base Ecosystem ───────────────────────────────────────────────────────────

  {
    id: "base-grant-finder",
    name: "Base Grant Finder",
    description: "Find active grants, hackathons, and funding programs for Base builders.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "base-ecosystem",
    inputs: [
      { key: "project", label: "Project type / description", placeholder: "What you're building — be specific about the category", required: true },
      { key: "stage", label: "Stage", placeholder: "e.g. idea, MVP, live product with users" },
    ],
    isComposite: true,
    price: "$0.20",
    priceUSDC: 200000,
    x402Url: `${X402_BASE}/base-grant-finder`,
    x402Body: (v) => ({ project: v.project ?? "", stage: v.stage ?? "early", sector: "Base ecosystem" }),
  },
  {
    id: "base-protocol-comparison",
    name: "Base Protocol Comparison",
    description: "Side-by-side comparison of Base protocols for integrations and partnerships.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "base-ecosystem",
    inputs: [
      { key: "protocol_a", label: "Protocol A", placeholder: "e.g. Aerodrome, Aave, Uniswap v4", required: true },
      { key: "protocol_b", label: "Protocol B", placeholder: "e.g. Morpho, Curve, Seamless", required: true },
      { key: "use_case", label: "Your use case", placeholder: "What do you need this protocol for?" },
    ],
    isComposite: true,
    price: "$0.25",
    priceUSDC: 250000,
    x402Url: `${X402_BASE}/base-protocol-comparison`,
    x402Body: (v) => ({ protocol_a: v.protocol_a ?? "", protocol_b: v.protocol_b ?? "", category: "Base DeFi", use_case: v.use_case ?? "" }),
  },
  {
    id: "base-builder-network-match",
    name: "Builder Network Match",
    description: "Connect with Base builders who complement your skill set and project.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "base-ecosystem",
    inputs: [
      { key: "skills", label: "Your skills", placeholder: "e.g. Solidity, frontend, product, BD, design", required: true },
      { key: "looking_for", label: "Looking for", placeholder: "e.g. co-founder, technical advisor, growth lead" },
    ],
    isComposite: true,
    price: "$0.20",
    priceUSDC: 200000,
    x402Url: `${X402_BASE}/base-builder-network-match`,
    x402Body: (v) => ({ skills: v.skills ?? "", looking_for: v.looking_for ?? "" }),
  },

  // ── On-chain Strategy ────────────────────────────────────────────────────────

  {
    id: "wallet-strategy-analyzer",
    name: "Wallet Strategy Analyzer",
    description: "Deep analysis of any wallet's on-chain strategy, behavior patterns, and alpha signals.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "on-chain",
    inputs: [
      { key: "address", label: "Wallet address", placeholder: "0x… Base wallet address", required: true },
      { key: "focus", label: "Analysis focus (optional)", placeholder: "e.g. trading patterns, DeFi activity, token accumulation" },
    ],
    isComposite: true,
    price: "$0.30",
    priceUSDC: 300000,
    x402Url: `${X402_BASE}/wallet-strategy-analyzer`,
    x402Body: (v) => ({ address: v.address ?? "", focus: v.focus ?? "" }),
  },
  {
    id: "protocol-risk-monitor",
    name: "Protocol Risk Monitor",
    description: "Real-time risk assessment for your DeFi positions — exit signals, risk scores.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "on-chain",
    inputs: [
      { key: "protocol", label: "Protocol", placeholder: "e.g. Aerodrome, Aave Base, Uniswap v4, Morpho", required: true },
      { key: "position", label: "Position details (optional)", placeholder: "e.g. ETH/USDC LP, $5k USDC lend — helps get specific risk analysis" },
    ],
    isComposite: true,
    price: "$0.35",
    priceUSDC: 350000,
    x402Url: `${X402_BASE}/protocol-risk-monitor`,
    x402Body: (v) => ({ protocol: v.protocol ?? "", position: v.position ?? "" }),
  },

  // ── Console commands (paid x402) ────────────────────────────────────────────
  {
    id: "honeypot-check",
    name: "Honeypot Check",
    description: "Detect honeypot tokens that can be bought but not sold. Transfer tax analysis + rug pattern detection on Base.",
    agentHandle: "composite",
    agentName: "Blue + MiroShark",
    agentType: "composite",
    category: "security",
    inputs: [
      { key: "token", label: "Token contract address", placeholder: "0x...", required: true },
    ],
    isComposite: true,
    compositeSkills: [
      { agentType: "blue", label: "Honeypot detection" },
      { agentType: "miroshark", label: "Community rug signal" },
    ],
    featured: false,
    price: "$0.10", priceUSDC: 100000,
    x402Url: `https://blueagent.dev/api/x402/honeypot-check`,
    x402Body: (v) => ({ token: v.token ?? "" }),
  },
  {
    id: "risk-gate",
    name: "Risk Gate",
    description: "Pre-transaction risk assessment — screen any address or swap for drainer patterns, AML signals, and malicious contracts.",
    agentHandle: "composite",
    agentName: "Blue + MiroShark",
    agentType: "composite",
    category: "security",
    inputs: [
      { key: "to", label: "Target address", placeholder: "0x...", required: true },
      { key: "action", label: "Action type", placeholder: "transfer | swap | approve | call", required: false },
      { key: "value", label: "Amount in Wei (optional)", placeholder: "1000000000000000000", required: false },
    ],
    isComposite: true,
    compositeSkills: [
      { agentType: "blue", label: "Risk assessment" },
      { agentType: "miroshark", label: "AML + community signal" },
    ],
    featured: false,
    price: "$0.20", priceUSDC: 200000,
    x402Url: `https://blueagent.dev/api/x402/risk-gate`,
    x402Body: (v) => ({ to: v.to ?? "", action: v.action ?? "transfer", value: v.value ?? "" }),
  },
  {
    id: "deep-analysis",
    name: "Deep Analysis",
    description: "Full due diligence on any Base token — security score, market fundamentals, on-chain activity, and composite verdict.",
    agentHandle: "composite",
    agentName: "Blue + Aeon + MiroShark",
    agentType: "composite",
    category: "security",
    inputs: [
      { key: "token", label: "Token contract address", placeholder: "0x...", required: true },
      { key: "context", label: "Additional context (optional)", placeholder: "e.g. new Uniswap v4 pool token", required: false },
    ],
    isComposite: true,
    compositeSkills: [
      { agentType: "blue", label: "Security deep dive" },
      { agentType: "miroshark", label: "Market + community signal" },
      { agentType: "aeon", label: "On-chain fundamentals" },
    ],
    featured: false,
    price: "$0.50", priceUSDC: 500000,
    x402Url: `https://blueagent.dev/api/x402/deep-analysis`,
    x402Body: (v) => ({ token: v.token ?? "", context: v.context ?? "" }),
  },
  {
    id: "builder-score",
    name: "Builder Score",
    description: "Builder reputation score (0-100) for any X/Twitter handle — on-chain activity, shipping history, Base ecosystem credibility.",
    agentHandle: "composite",
    agentName: "Blue + MiroShark",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "handle", label: "X/Twitter handle (without @)", placeholder: "blueagent_", required: true },
    ],
    isComposite: true,
    compositeSkills: [
      { agentType: "blue", label: "Builder credibility" },
      { agentType: "miroshark", label: "Community reputation" },
    ],
    featured: false,
    price: "$0.35", priceUSDC: 350000,
    x402Url: `https://blueagent.dev/api/x402/builder-score`,
    x402Body: (v) => ({ handle: v.handle ?? "" }),
  },
  {
    id: "agent-score",
    name: "Agent Score",
    description: "Performance score for AI agents on Base — XP, interaction volume, uptime, ecosystem impact.",
    agentHandle: "composite",
    agentName: "Blue + MiroShark",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "handle", label: "Agent handle or name", placeholder: "blueagent_", required: true },
    ],
    isComposite: true,
    compositeSkills: [
      { agentType: "blue", label: "Agent performance" },
      { agentType: "miroshark", label: "Ecosystem impact" },
    ],
    featured: false,
    price: "$0.35", priceUSDC: 350000,
    x402Url: `https://blueagent.dev/api/x402/agent-score`,
    x402Body: (v) => ({ handle: v.handle ?? "" }),
  },
  {
    id: "contract-trust",
    name: "Contract Trust",
    description: "Audit any Base contract before swapping or interacting. Basescan verification + security scan + community signal. Verdict: SAFE / CAUTION / RED_FLAG.",
    agentHandle: "composite",
    agentName: "Blue + MiroShark",
    agentType: "composite",
    category: "security",
    inputs: [
      { key: "address", label: "Contract address", placeholder: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913", required: true },
      { key: "context", label: "What is this contract? (optional)", placeholder: "USDC token on Base", required: false },
    ],
    isComposite: true,
    compositeSkills: [
      { agentType: "blue", label: "Security analysis" },
      { agentType: "miroshark", label: "Community trust signal" },
    ],
    featured: false,
    price: "$0.15", priceUSDC: 150000,
    x402Url: `https://blueagent.dev/api/x402/contract-trust`,
    x402Body: (v) => ({ address: v.address ?? "", context: v.context ?? "" }),
  },
  {
    id: "blue-idea",
    name: "Blue Idea",
    description: "Turn a rough concept into a fundable brief — problem, why now, why Base, MVP scope, risks, 24h plan.",
    agentHandle: "blue", agentName: "Blue", agentType: "blue",
    category: "builder",
    inputs: [{ key: "prompt", label: "Your idea or concept", placeholder: "A USDC streaming payroll app for DAOs on Base", required: true }],
    isComposite: false,
    price: "$0.05", priceUSDC: 50000,
    x402Url: `${X402_BASE}/blue-idea`,
    x402Body: (v) => ({ prompt: v.prompt ?? "" }),
  },
  {
    id: "blue-build",
    name: "Blue Build",
    description: "Architecture, stack, folder structure, integrations, test plan. Verified Base patterns, no hallucinations.",
    agentHandle: "blue", agentName: "Blue", agentType: "blue",
    category: "builder",
    inputs: [{ key: "prompt", label: "What you're building", placeholder: "Build a token-gated API with x402 payments on Base", required: true }],
    isComposite: false,
    price: "$0.50", priceUSDC: 500000,
    x402Url: `${X402_BASE}/blue-build`,
    x402Body: (v) => ({ prompt: v.prompt ?? "" }),
  },
  {
    id: "blue-audit",
    name: "Blue Audit",
    description: "Security + product risk review. Reentrancy, oracle, MEV, x402, Coinbase Smart Wallet. Go/no-go.",
    agentHandle: "blue", agentName: "Blue", agentType: "blue",
    category: "builder",
    inputs: [{ key: "prompt", label: "Code, contract, or system to audit", placeholder: "Paste contract code or paste system description", required: true }],
    isComposite: false,
    price: "$1.00", priceUSDC: 1000000,
    x402Url: `${X402_BASE}/blue-audit`,
    x402Body: (v) => ({ prompt: v.prompt ?? "" }),
  },
  {
    id: "blue-ship",
    name: "Blue Ship",
    description: "Deployment checklist, verification, release notes, monitoring. Everything you forget when excited to launch.",
    agentHandle: "blue", agentName: "Blue", agentType: "blue",
    category: "builder",
    inputs: [{ key: "prompt", label: "What you're shipping", placeholder: "Ship my Uniswap v4 hook to Base mainnet", required: true }],
    isComposite: false,
    price: "$0.10", priceUSDC: 100000,
    x402Url: `${X402_BASE}/blue-ship`,
    x402Body: (v) => ({ prompt: v.prompt ?? "" }),
  },
  {
    id: "blue-raise",
    name: "Blue Raise",
    description: "Fundraising narrative, investor deck outline, smart money map, competitive landscape for your Base niche.",
    agentHandle: "blue", agentName: "Blue", agentType: "blue",
    category: "builder",
    inputs: [{ key: "prompt", label: "Project + raise context", placeholder: "Raise a pre-seed for my Base DeFi protocol", required: true }],
    isComposite: false,
    price: "$0.20", priceUSDC: 200000,
    x402Url: `${X402_BASE}/blue-raise`,
    x402Body: (v) => ({ prompt: v.prompt ?? "" }),
  },
  {
    id: "blue-monitor",
    name: "Blue Monitor",
    description: "On-demand health + risk snapshot for a Base token/contract — live price, liquidity, verification, risk signals, and a watch plan with alert thresholds.",
    agentHandle: "blue", agentName: "Blue", agentType: "blue",
    category: "security",
    inputs: [
      { key: "target", label: "Target", placeholder: "0x… token/contract address, or a protocol name", required: true },
      { key: "focus", label: "Focus (optional)", placeholder: "e.g. liquidity, exit risk, contract changes" },
    ],
    isComposite: false,
    price: "$0.20", priceUSDC: 200000,
    x402Url: `${X402_BASE}/blue-monitor`,
    x402Body: (v) => ({ target: v.target ?? "", focus: v.focus ?? "" }),
  },
  {
    id: "blue-registry",
    name: "Blue Registry",
    description: "Discover the Blue Hub tool catalog — every callable x402 tool (first-party + community), filterable by query/category, with prices and how-to-call.",
    agentHandle: "blue", agentName: "Blue", agentType: "blue",
    category: "builder",
    inputs: [
      { key: "query", label: "Search (optional)", placeholder: "e.g. honeypot, token, audit" },
      { key: "category", label: "Category (optional)", placeholder: "e.g. security, intelligence, builder" },
    ],
    isComposite: false,
    price: "$0.05", priceUSDC: 50000,
    x402Url: `${X402_BASE}/blue-registry`,
    x402Body: (v) => ({ query: v.query ?? "", category: v.category ?? "" }),
  },
  {
    id: "blue-research",
    name: "Blue Research",
    description: "Deep DD memo on a Base project, narrative, or token — thesis, bull/bear, risks, contrarian take, verdict. Grounds in live market data when a token address is given.",
    agentHandle: "blue", agentName: "Blue", agentType: "blue",
    category: "intelligence",
    inputs: [
      { key: "topic", label: "Topic / project", placeholder: "e.g. Base restaking, or a protocol name", required: true },
      { key: "target", label: "Token address (optional)", placeholder: "0x… to ground in live market data" },
    ],
    isComposite: false,
    price: "$1.00", priceUSDC: 1000000,
    x402Url: `${X402_BASE}/blue-research`,
    x402Body: (v) => ({ topic: v.topic ?? "", target: v.target ?? "" }),
  },
  {
    id: "blue-compose",
    name: "Blue Compose",
    description: "Turn a goal into a runnable chain of Blue Hub tools — picks from the real catalog, orders them, suggests inputs, and estimates cost.",
    agentHandle: "blue", agentName: "Blue", agentType: "blue",
    category: "builder",
    inputs: [
      { key: "goal", label: "Goal", placeholder: "e.g. take my Base DeFi idea from concept to audited + funded", required: true },
    ],
    isComposite: false,
    price: "$0.10", priceUSDC: 100000,
    x402Url: `${X402_BASE}/blue-compose`,
    x402Body: (v) => ({ goal: v.goal ?? "" }),
  },
  {
    id: "blue-deploy",
    name: "Blue Deploy",
    description: "Technical deploy mechanics for Base mainnet — deploy scripts, Basescan verify commands, env vars, gas notes, post-deploy checks. Never invents addresses.",
    agentHandle: "blue", agentName: "Blue", agentType: "blue",
    category: "builder",
    inputs: [
      { key: "project", label: "What you're deploying", placeholder: "e.g. an ERC-20 + staking contract (Foundry)", required: true },
      { key: "stack", label: "Stack (optional)", placeholder: "e.g. Foundry, Hardhat, viem" },
    ],
    isComposite: false,
    price: "$0.10", priceUSDC: 100000,
    x402Url: `${X402_BASE}/blue-deploy`,
    x402Body: (v) => ({ project: v.project ?? "", stack: v.stack ?? "" }),
  },
  {
    id: "blue-analytics",
    name: "Blue Analytics",
    description: "Performance/metrics read on a Base token — live price, momentum, liquidity health, volume/liquidity ratio, growth signals. Real DexScreener data.",
    agentHandle: "blue", agentName: "Blue", agentType: "blue",
    category: "intelligence",
    inputs: [
      { key: "target", label: "Token address", placeholder: "0x… Base token contract", required: true },
      { key: "focus", label: "Focus (optional)", placeholder: "e.g. momentum, liquidity, accumulation" },
    ],
    isComposite: false,
    price: "$0.25", priceUSDC: 250000,
    x402Url: `${X402_BASE}/blue-analytics`,
    x402Body: (v) => ({ target: v.target ?? "", focus: v.focus ?? "" }),
  },
  {
    id: "blue-simulate",
    name: "Blue Simulate",
    description: "Bull/base/bear scenario modeling for a Base decision — tokenomics, fee model, growth, runway — with assumptions, projections, and sensitivities.",
    agentHandle: "blue", agentName: "Blue", agentType: "blue",
    category: "builder",
    inputs: [
      { key: "scenario", label: "What to simulate", placeholder: "e.g. fee model at 0.3% vs 1% over 12 months", required: true },
      { key: "params", label: "Parameters (optional)", placeholder: "e.g. 10k users, $2M TVL, 5% monthly growth" },
    ],
    isComposite: false,
    price: "$0.15", priceUSDC: 150000,
    x402Url: `${X402_BASE}/blue-simulate`,
    x402Body: (v) => ({ scenario: v.scenario ?? "", params: v.params ?? "" }),
  },
  {
    id: "blue-stream",
    name: "Blue Stream",
    description: "Live snapshot feed of Base onchain activity — trending & new pools, TVL, real price/volume/liquidity. Pure real data, poll for a near-real-time feed.",
    agentHandle: "blue", agentName: "Blue", agentType: "blue",
    category: "on-chain",
    inputs: [
      { key: "feed", label: "Feed", placeholder: "movers | new | all (default: movers)" },
    ],
    isComposite: false,
    price: "$0.05", priceUSDC: 50000,
    x402Url: `${X402_BASE}/blue-stream`,
    x402Body: (v) => ({ feed: v.feed ?? "movers" }),
  },

{
    id: "wallet-pnl",
    name: "Wallet PnL Report",
    description: "Wallet PnL report — trading style, win rate, smart money score, top tokens on Base.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "on-chain",
    inputs: [
      { key: "address", label: "Base wallet address", placeholder: "0x...", required: true },
    ],
    isComposite: true,
    price: "$1.00", priceUSDC: 1000000,
    x402Url: `${X402_BASE}/wallet-pnl`,
    x402Body: (v) => ({ address: v.address ?? "" }),
  },
  {
    id: "aml-screen",
    name: "AML Screen",
    description: "AML compliance screening for any wallet — transaction patterns, risk flags, clean/suspicious verdict.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "on-chain",
    inputs: [
      { key: "address", label: "Wallet address to screen", placeholder: "0x...", required: true },
    ],
    isComposite: true,
    price: "$0.25", priceUSDC: 250000,
    x402Url: `${X402_BASE}/aml-screen`,
    x402Body: (v) => ({ address: v.address ?? "" }),
  },
  {
    id: "airdrop-check",
    name: "Airdrop Check",
    description: "Base airdrop eligibility check — which protocols, activity score, estimated value.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "on-chain",
    inputs: [
      { key: "address", label: "Wallet address", placeholder: "0x...", required: true },
    ],
    isComposite: true,
    price: "$0.10", priceUSDC: 100000,
    x402Url: `${X402_BASE}/airdrop-check`,
    x402Body: (v) => ({ address: v.address ?? "" }),
  },
  {
    id: "whale-tracker",
    name: "Whale Tracker",
    description: "Smart money and whale flow analysis — accumulation vs distribution signal for any token.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "on-chain",
    inputs: [
      { key: "address", label: "Token or wallet address", placeholder: "0x...", required: true },
    ],
    isComposite: true,
    price: "$0.10", priceUSDC: 100000,
    x402Url: `${X402_BASE}/whale-tracker`,
    x402Body: (v) => ({ address: v.address ?? "" }),
  },
  {
    id: "dex-flow",
    name: "DEX Flow",
    description: "DEX volume, buy/sell pressure and liquidity flow for any Base token — live DexScreener data.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "on-chain",
    inputs: [
      { key: "token", label: "Token contract address or ticker", placeholder: "0x... or BRETT", required: true },
    ],
    isComposite: true,
    price: "$0.15", priceUSDC: 150000,
    x402Url: `${X402_BASE}/dex-flow`,
    x402Body: (v) => ({ token: v.token ?? "" }),
  },

  // ── Earn ─────────────────────────────────────────────────────────────────────

  {
    id: "yield-optimizer",
    name: "Yield Optimizer",
    description: "Best APY opportunities on Base DeFi — live DeFiLlama data, risk-adjusted recommendations.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "earn",
    inputs: [
      { key: "token", label: "Token to optimize yield for", placeholder: "USDC, ETH, BRETT", required: true },
    ],
    isComposite: true,
    price: "$0.15", priceUSDC: 150000,
    x402Url: `${X402_BASE}/yield-optimizer`,
    x402Body: (v) => ({ token: v.token ?? "" }),
  },
  {
    id: "lp-analyzer",
    name: "LP Analyzer",
    description: "LP position analysis — impermanent loss, fee income, rebalance recommendation.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "earn",
    inputs: [
      { key: "token0", label: "Token 0", placeholder: "ETH or 0x...", required: true },
      { key: "token1", label: "Token 1", placeholder: "USDC or 0x..." },
      { key: "entryPrice", label: "Entry price (optional)", placeholder: "e.g. 2400" },
      { key: "investedAmount", label: "Invested amount USD (optional)", placeholder: "e.g. 5000" },
    ],
    isComposite: true,
    price: "$0.25", priceUSDC: 250000,
    x402Url: `${X402_BASE}/lp-analyzer`,
    x402Body: (v) => ({ token0: v.token0 ?? "", token1: v.token1 ?? "", entryPrice: v.entryPrice ?? "", investedAmount: v.investedAmount ?? "" }),
  },
  {
    id: "tax-report",
    name: "Tax Report",
    description: "On-chain tax summary — realized gains, taxable events, P&L.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "earn",
    inputs: [
      { key: "address", label: "Wallet address", placeholder: "0x...", required: true },
      { key: "year", label: "Tax year (optional)", placeholder: "e.g. 2024" },
      { key: "country", label: "Country (optional)", placeholder: "US, UK, etc." },
    ],
    isComposite: true,
    price: "$2.00", priceUSDC: 2000000,
    x402Url: `${X402_BASE}/tax-report`,
    x402Body: (v) => ({ address: v.address ?? "", year: v.year ?? "", country: v.country ?? "US" }),
  },

  // ── Alerts ───────────────────────────────────────────────────────────────────

  {
    id: "alert-subscribe",
    name: "Alert Subscribe",
    description: "Subscribe to real-time alerts via webhook — whale, circuit breaker, quantum exposure.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "alerts",
    inputs: [
      { key: "webhookUrl", label: "Webhook URL", placeholder: "https://your-server.com/webhook", required: true },
      { key: "topics", label: "Topics (comma-separated)", placeholder: "whale_movement, rug_risk, quantum_exposure", required: true },
      { key: "addresses", label: "Addresses to watch (optional)", placeholder: "0x..., 0x... or leave blank for global" },
    ],
    isComposite: true,
    price: "$0.50", priceUSDC: 500000,
    x402Url: `${X402_BASE}/alert-subscribe`,
    x402Body: (v) => ({
      webhookUrl: v.webhookUrl ?? "",
      topics: (v.topics ?? "").split(",").map((t: string) => t.trim()).filter(Boolean),
      addresses: v.addresses ? (v.addresses as string).split(",").map((a: string) => a.trim()).filter(Boolean) : [],
    }),
  },
  {
    id: "alert-check",
    name: "Alert Check",
    description: "Check active alert triggers for any address.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "alerts",
    inputs: [
      { key: "address", label: "Wallet or token address", placeholder: "0x...", required: true },
    ],
    isComposite: true,
    price: "$0.10", priceUSDC: 100000,
    x402Url: `${X402_BASE}/alert-check`,
    x402Body: (v) => ({ address: v.address ?? "" }),
  },

  // ── Builder (launch & grants) ─────────────────────────────────────────────────

  {
    id: "launch-simulator-2",
    name: "Launch Simulator Tier 2",
    description: "Deep Signal launch simulation with live DexScreener market data — price, volume, liquidity.",
    agentHandle: "composite", agentName: "Blue + Aeon + MiroShark", agentType: "composite",
    category: "builder",
    inputs: [
      { key: "project", label: "Project name", placeholder: "Your project name", required: true },
      { key: "description", label: "Project description", placeholder: "What it does, target audience, current stage" },
      { key: "ticker", label: "Token ticker (optional)", placeholder: "e.g. $BLUE" },
      { key: "contract", label: "Contract address (optional)", placeholder: "0x... for live market data" },
    ],
    isComposite: true,
    price: "$0.35", priceUSDC: 350000,
    x402Url: `${X402_BASE}/launch-simulator-2`,
    x402Body: (v) => ({ project: v.project ?? "", description: v.description ?? "", ticker: v.ticker ?? "", contract: v.contract ?? "" }),
  },
  {
    id: "launch-simulator-3",
    name: "Launch Simulator Tier 3",
    description: "Full Simulation — complete multi-agent report with risk matrix and timeline recommendation.",
    agentHandle: "composite", agentName: "Blue + Aeon + MiroShark", agentType: "composite",
    category: "builder",
    inputs: [
      { key: "project", label: "Project name", placeholder: "Your project name", required: true },
      { key: "description", label: "Project description", placeholder: "What it does, target audience, current stage" },
      { key: "ticker", label: "Token ticker (optional)", placeholder: "e.g. $BLUE" },
      { key: "contract", label: "Contract address (optional)", placeholder: "0x... for live market data" },
    ],
    isComposite: true,
    featured: true,
    price: "$0.50", priceUSDC: 500000,
    x402Url: `${X402_BASE}/launch-simulator-3`,
    x402Body: (v) => ({ project: v.project ?? "", description: v.description ?? "", ticker: v.ticker ?? "", contract: v.contract ?? "" }),
  },
  {
    id: "launch-advisor",
    name: "Launch Advisor",
    description: "Full token launch playbook — tokenomics, 8-week timeline, marketing strategy, KPIs.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "builder",
    inputs: [
      { key: "projectName", label: "Project name", placeholder: "Your project name", required: true },
      { key: "description", label: "Project description", placeholder: "What it does, why Base, target users", required: true },
      { key: "targetAudience", label: "Target audience (optional)", placeholder: "e.g. Base builders and DeFi traders" },
      { key: "teamSize", label: "Team size (optional)", placeholder: "e.g. solo, 3 people" },
      { key: "budget", label: "Budget (optional)", placeholder: "e.g. $10k for launch" },
      { key: "tokenSupply", label: "Token supply (optional)", placeholder: "e.g. 1,000,000,000" },
    ],
    isComposite: true,
    price: "$3.00", priceUSDC: 3000000,
    x402Url: `${X402_BASE}/launch-advisor`,
    x402Body: (v) => ({ projectName: v.projectName ?? "", description: v.description ?? "", targetAudience: v.targetAudience ?? "", teamSize: v.teamSize ?? "", budget: v.budget ?? "", tokenSupply: v.tokenSupply ?? "" }),
  },
  {
    id: "grant-evaluator",
    name: "Grant Evaluator",
    description: "Base ecosystem grant scoring — innovation, feasibility, impact, team quality.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "builder",
    inputs: [
      { key: "projectName", label: "Project name", placeholder: "Your project name", required: true },
      { key: "description", label: "Project description", placeholder: "What you're building and why it matters for Base", required: true },
      { key: "teamBackground", label: "Team background (optional)", placeholder: "Experience, previous projects, GitHub" },
      { key: "requestedAmount", label: "Requested grant amount (optional)", placeholder: "e.g. $25,000" },
      { key: "milestones", label: "Milestones (optional)", placeholder: "What you'll deliver and when" },
      { key: "githubUrl", label: "GitHub URL (optional)", placeholder: "https://github.com/..." },
    ],
    isComposite: true,
    price: "$5.00", priceUSDC: 5000000,
    x402Url: `${X402_BASE}/grant-evaluator`,
    x402Body: (v) => ({ projectName: v.projectName ?? "", description: v.description ?? "", teamBackground: v.teamBackground ?? "", requestedAmount: v.requestedAmount ?? "", milestones: v.milestones ?? "", githubUrl: v.githubUrl ?? "" }),
  },
];

// ─── v2 defaults ──────────────────────────────────────────────────────────────
// Centralize verified/aiReady/builder defaults so we don't have to set them on
// every tool. Builder-submitted tools (Phase 3) override these explicitly.

const DEFAULT_RELEASED_AT = new Date("2024-06-01T00:00:00Z").getTime();

function withV2Defaults(t: AgentTool): AgentTool {
  return {
    ...t,
    verified:       t.verified       ?? true,            // first-party = pre-verified
    aiReady:        t.aiReady        ?? true,            // all current tools return JSON
    builderAddress: t.builderAddress ?? BLUE_TREASURY,
    releasedAt:     t.releasedAt     ?? DEFAULT_RELEASED_AT,
  };
}

export const AGENT_TOOLS: AgentTool[] = AGENT_TOOLS_RAW.map(withV2Defaults);
