// ─── Agent Tool types & seeded data ──────────────────────────────────────────

export type AgentToolInput = {
  key: string;
  label: string;
  placeholder: string;
  required?: boolean;
};

export type CompositeSkill = {
  agentType: "aeon" | "blue" | "miroshark";
  skillId?: string;
  skillFiles?: string[];
  label: string;
};

const X402_BASE = "https://blueagent.dev/api/x402";

// Blue Hub treasury — default builder address for Blue Agent first-party tools.
// Builder-submitted tools (Hub v2 Phase 3) will set this to the builder's own wallet.
export const BLUE_TREASURY = "0xb058a1e305d9c720aa5b1bf42b6f2f6294b03b5f" as const;

export type AgentTool = {
  id: string;
  name: string;
  description: string;
  agentHandle: string;
  agentName: string;
  agentType: "aeon" | "blue" | "miroshark" | "composite";
  category: string;
  skillId?: string;
  skillFiles?: string[];
  inputs: AgentToolInput[];
  isComposite: boolean;
  compositeSkills?: CompositeSkill[];
  featured?: boolean;
  // x402 payment
  price?: string;          // e.g. "$0.20"
  priceUSDC?: number;      // in USDC units (6 decimals), e.g. 200000 = $0.20
  x402Url?: string;        // full x402 endpoint URL — if set, payment is required
  x402Body?: (values: Record<string, string>) => Record<string, unknown>; // maps hub inputs → x402 body
  // v2 marketplace metadata — defaults applied via withV2Defaults() at bottom of file
  verified?:       boolean;          // Blue Agent reviewed; default true for first-party
  aiReady?:        boolean;          // Returns structured JSON; default true
  builderAddress?: `0x${string}`;    // Revenue recipient; default BLUE_TREASURY
  releasedAt?:    number;            // Unix ms — drives "Newest" sort; default 2024-06-01
};

// ─── All 70 tools ─────────────────────────────────────────────────────────────

const AGENT_TOOLS_RAW: AgentTool[] = [

  // ── New tools batch (20) ──
  {
    id: "token-price",
    name: "Token Price",
    description: "Live price, mcap, volume and liquidity for any Base token (DexScreener).",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "on-chain",
    inputs: [
      { key: "token", label: "Token address or ticker", placeholder: "0x… or AERO", required: true },
    ],
    isComposite: true,
    price: "$0.01", priceUSDC: 10000,
    x402Url: `${X402_BASE}/token-price`,
    x402Body: (v) => ({ token: v.token ?? "" }),
  },
  {
    id: "pool-scan",
    name: "Pool Scan",
    description: "Trending + newly-active Base pools with the chain TVL snapshot.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "on-chain",
    inputs: [
      { key: "limit", label: "Limit (optional)", placeholder: "10" },
    ],
    isComposite: true,
    price: "$0.02", priceUSDC: 20000,
    x402Url: `${X402_BASE}/pool-scan`,
    x402Body: (v) => ({ limit: v.limit ? Number(v.limit) : 10 }),
  },
  {
    id: "wallet-holdings",
    name: "Wallet Holdings",
    description: "Live ERC-20 + ETH holdings and USD value for a Base wallet (Moralis).",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "on-chain",
    inputs: [
      { key: "address", label: "Wallet address", placeholder: "0x…", required: true },
    ],
    isComposite: true,
    price: "$0.02", priceUSDC: 20000,
    x402Url: `${X402_BASE}/wallet-holdings`,
    x402Body: (v) => ({ address: v.address ?? "" }),
  },
  {
    id: "new-pools",
    name: "New Pools",
    description: "Freshly-created Base pools with thin-liquidity honeypot flags.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "on-chain",
    inputs: [
      { key: "hours", label: "Window hours (optional)", placeholder: "24" },
    ],
    isComposite: true,
    price: "$0.02", priceUSDC: 20000,
    x402Url: `${X402_BASE}/new-pools`,
    x402Body: (v) => ({ hours: v.hours ? Number(v.hours) : 24 }),
  },
  {
    id: "gas-tracker",
    name: "Gas Tracker",
    description: "Live Base gas price + USD cost estimates for common actions.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "on-chain",
    inputs: [],
    isComposite: true,
    price: "$0.01", priceUSDC: 10000,
    x402Url: `${X402_BASE}/gas-tracker`,
    x402Body: (v) => ({}),
  },
  {
    id: "quick-safety",
    name: "Quick Safety",
    description: "Fast contract safety check — liquidity, verification, risk verdict.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "security",
    inputs: [
      { key: "contract", label: "Contract address", placeholder: "0x…", required: true },
    ],
    isComposite: true,
    price: "$0.05", priceUSDC: 50000,
    x402Url: `${X402_BASE}/quick-safety`,
    x402Body: (v) => ({ contract: v.contract ?? "" }),
  },
  {
    id: "wallet-risk",
    name: "Wallet Risk",
    description: "AML / risk screen for a Base wallet from real on-chain flow (Moralis).",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "security",
    inputs: [
      { key: "address", label: "Wallet address", placeholder: "0x…", required: true },
    ],
    isComposite: true,
    price: "$0.05", priceUSDC: 50000,
    x402Url: `${X402_BASE}/wallet-risk`,
    x402Body: (v) => ({ address: v.address ?? "" }),
  },
  {
    id: "b20-check",
    name: "B20 Check",
    description: "ERC-20 compliance (B20) role + policy detection from verified source.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "security",
    inputs: [
      { key: "contract", label: "Contract address", placeholder: "0x…", required: true },
    ],
    isComposite: true,
    price: "$0.05", priceUSDC: 50000,
    x402Url: `${X402_BASE}/b20-check`,
    x402Body: (v) => ({ contract: v.contract ?? "" }),
  },
  {
    id: "b20-analyze",
    name: "B20 Analyze",
    description: "B20 (Base Native Token Standard) guide — variants, roles, policies, integration tips. Powered by Beryl upgrade docs.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "security",
    inputs: [
      { key: "action", label: "Action", placeholder: "guide / roles / policy / analyze / compare", required: false },
      { key: "address", label: "Token address (optional)", placeholder: "0x…", required: false },
      { key: "context", label: "Context (optional)", placeholder: "Describe your use case", required: false },
    ],
    isComposite: true,
    price: "$0.05", priceUSDC: 50000,
    x402Url: `${X402_BASE}/b20-analyze`,
    x402Body: (v) => ({ action: v.action ?? "guide", address: v.address, context: v.context }),
  },
  {
    id: "b20-tracker",
    name: "B20 Tracker",
    description: "Live B20 activity on Base — B20-related launches and Beryl activation status. Distinguishes B20-themed tokens from native B20 standard.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "data",
    inputs: [],
    isComposite: true,
    price: "$0.05", priceUSDC: 50000,
    x402Url: `${X402_BASE}/b20-tracker`,
    x402Body: () => ({}),
  },
  {
    id: "b20-launch",
    name: "B20 Launch",
    description: "Generate complete B20 token deployment package — foundry.toml, Solidity deploy script, setup + deploy + mint commands. Input: name, symbol, variant (asset/stablecoin), optional supply_cap/currency_code.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "security",
    inputs: [
      { key: "name",          label: "Token name",   placeholder: "e.g. MyToken",              required: true  },
      { key: "symbol",        label: "Symbol",        placeholder: "e.g. MTK",                  required: true  },
      { key: "variant",       label: "Variant",       placeholder: "asset or stablecoin",        required: true  },
      { key: "decimals",      label: "Decimals",      placeholder: "18 (default)",               required: false },
      { key: "supply_cap",    label: "Supply cap",    placeholder: "e.g. 1000000 (optional)",    required: false },
      { key: "currency_code", label: "Currency code", placeholder: "USD (stablecoin only)",      required: false },
    ],
    isComposite: true,
    price: "$0.25", priceUSDC: 250000,
    x402Url: `${X402_BASE}/b20-launch`,
    x402Body: (v) => ({
      name: v.name, symbol: v.symbol, variant: v.variant ?? "asset",
      decimals: v.decimals ? Number(v.decimals) : undefined,
      supply_cap: v.supply_cap ? Number(v.supply_cap) : undefined,
      currency_code: v.currency_code,
    }),
  },
  {
    id: "b20-inspect",
    name: "B20 Inspect",
    description: "Live on-chain B20 token inspector — reads real state from Base RPC via multicall. Returns isB20 flag, name/symbol/decimals, totalSupply, supplyCap, variant (ASSET/STABLECOIN), pause status per feature, and policy IDs per transfer/mint scope. Zero LLM.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "security",
    inputs: [
      { key: "address", label: "Token address", placeholder: "0x… (B20 token on Base)", required: true  },
      { key: "network", label: "Network",        placeholder: "mainnet (default) or sepolia",             required: false },
    ],
    isComposite: true,
    price: "$0.005", priceUSDC: 5000,
    x402Url: `${X402_BASE}/b20-inspect`,
    x402Body: (v) => ({ address: v.address ?? "", network: v.network ?? "mainnet" }),
  },
  {
    id: "liquidity-depth",
    name: "Liquidity Depth",
    description: "Liquidity depth, slippage estimate and exit risk for a Base token.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "security",
    inputs: [
      { key: "token", label: "Token address or ticker", placeholder: "0x… or AERO", required: true },
    ],
    isComposite: true,
    price: "$0.03", priceUSDC: 30000,
    x402Url: `${X402_BASE}/liquidity-depth`,
    x402Body: (v) => ({ token: v.token ?? "", trade_size_usd: v.trade_size_usd ? Number(v.trade_size_usd) : undefined }),
  },
  {
    id: "token-distribution",
    name: "Token Distribution",
    description: "Holder concentration + rug-risk distribution score (Moralis holders).",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "security",
    inputs: [
      { key: "contract", label: "Contract address", placeholder: "0x…", required: true },
    ],
    isComposite: true,
    price: "$0.05", priceUSDC: 50000,
    x402Url: `${X402_BASE}/token-distribution`,
    x402Body: (v) => ({ contract: v.contract ?? "" }),
  },
  {
    id: "base-alpha",
    name: "Base Alpha",
    description: "Base market alpha — narratives, momentum picks, divergence signals.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "intelligence",
    inputs: [],
    isComposite: true,
    price: "$0.10", priceUSDC: 100000,
    x402Url: `${X402_BASE}/base-alpha`,
    x402Body: (v) => ({}),
  },
  {
    id: "token-alpha",
    name: "Token Alpha",
    description: "Token trade signal — entry, whale confirmation, momentum and risk.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "intelligence",
    inputs: [
      { key: "token", label: "Token address or ticker", placeholder: "0x… or AERO", required: true },
    ],
    isComposite: true,
    price: "$0.15", priceUSDC: 150000,
    x402Url: `${X402_BASE}/token-alpha`,
    x402Body: (v) => ({ token: v.token ?? "" }),
  },
  {
    id: "protocol-health",
    name: "Protocol Health",
    description: "Protocol TVL health, trend and risk signals (DefiLlama).",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "intelligence",
    inputs: [
      { key: "protocol", label: "Protocol name", placeholder: "Aerodrome", required: true },
    ],
    isComposite: true,
    price: "$0.10", priceUSDC: 100000,
    x402Url: `${X402_BASE}/protocol-health`,
    x402Body: (v) => ({ protocol: v.protocol ?? "" }),
  },
  {
    id: "founder-check",
    name: "Founder Check",
    description: "GitHub-based founder trust score — repos, stars, activity.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "intelligence",
    inputs: [
      { key: "handle", label: "GitHub handle", placeholder: "madebyshun", required: true },
    ],
    isComposite: true,
    price: "$0.10", priceUSDC: 100000,
    x402Url: `${X402_BASE}/founder-check`,
    x402Body: (v) => ({ handle: v.handle ?? "" }),
  },
  {
    id: "narrative-pulse",
    name: "Narrative Pulse",
    description: "Live Base narrative phases, velocity and entry windows.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "intelligence",
    inputs: [
      { key: "focus", label: "Focus (optional)", placeholder: "AI agents, RWA" },
    ],
    isComposite: true,
    price: "$0.10", priceUSDC: 100000,
    x402Url: `${X402_BASE}/narrative-pulse`,
    x402Body: (v) => ({ focus: v.focus ?? "" }),
  },
  {
    id: "base-activity-score",
    name: "Base Activity Score",
    description: "Onchain activity score + tier for a Base wallet (Moralis).",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "on-chain",
    inputs: [
      { key: "address", label: "Wallet address", placeholder: "0x…", required: true },
    ],
    isComposite: true,
    price: "$0.05", priceUSDC: 50000,
    x402Url: `${X402_BASE}/base-activity-score`,
    x402Body: (v) => ({ address: v.address ?? "" }),
  },
  {
    id: "scam-detector",
    name: "Scam Detector",
    description: "Detect honeypot / rug / fake-token patterns on a Base contract.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "on-chain",
    inputs: [
      { key: "contract", label: "Contract address", placeholder: "0x…", required: true },
    ],
    isComposite: true,
    price: "$0.10", priceUSDC: 100000,
    x402Url: `${X402_BASE}/scam-detector`,
    x402Body: (v) => ({ contract: v.contract ?? "" }),
  },
  {
    id: "cross-protocol-yield",
    name: "Cross-Protocol Yield",
    description: "Best Base yield for a token across protocols (DefiLlama).",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "on-chain",
    inputs: [
      { key: "token", label: "Token address or ticker", placeholder: "0x… or AERO", required: true },
    ],
    isComposite: true,
    price: "$0.15", priceUSDC: 150000,
    x402Url: `${X402_BASE}/cross-protocol-yield`,
    x402Body: (v) => ({ token: v.token ?? "", risk_tolerance: v.risk_tolerance ?? "medium" }),
  },
  {
    id: "agent-readiness",
    name: "Agent Readiness",
    description: "x402 + MCP readiness probe for an agent endpoint.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "on-chain",
    inputs: [
      { key: "url", label: "Endpoint URL", placeholder: "https://…", required: true },
    ],
    isComposite: true,
    price: "$0.10", priceUSDC: 100000,
    x402Url: `${X402_BASE}/agent-readiness`,
    x402Body: (v) => ({ url: v.url ?? "" }),
  },
  {
    id: "base-pulse",
    name: "Base Pulse",
    description: "Base chain market pulse — TVL, DEX volume, sentiment, pulse score.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "on-chain",
    inputs: [],
    isComposite: true,
    price: "$0.05", priceUSDC: 50000,
    x402Url: `${X402_BASE}/base-pulse`,
    x402Body: (v) => ({}),
  },

  // ── Intelligence ────────────────────────────────────────────────────────────

  {
    id: "token-pick-signal",
    name: "Token Pick Signal",
    description: "AI consensus on the highest-conviction asymmetric token setup on Base right now.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "intelligence",
    skillId: "token-pick",
    inputs: [
      { key: "context", label: "Market context (optional)", placeholder: "optional — leave blank for best pick, or add a focus (e.g. rising volume, a sector)" },
    ],
    isComposite: true,
    featured: true,
    price: "$0.20",
    priceUSDC: 200000,
    x402Url: `${X402_BASE}/token-pick-signal`,
    x402Body: (v) => ({ chain: "base", context: v.context ?? "" }),
  },
  {
    id: "narrative-position",
    name: "Narrative Position",
    description: "Which narratives are building vs peaking on CT — and where to position.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "intelligence",
    skillId: "narrative-tracker",
    inputs: [
      { key: "focus", label: "Narrative focus (optional)", placeholder: "e.g. AI agents, RWA, Base DeFi" },
    ],
    isComposite: true,
    featured: true,
    price: "$0.15",
    priceUSDC: 150000,
    x402Url: `${X402_BASE}/narrative-position`,
    x402Body: (v) => ({ topic: v.focus ?? "", focus: v.focus ?? "" }),
  },
  {
    id: "ecosystem-digest",
    name: "Ecosystem Digest",
    description: "Weekly Base ecosystem intelligence: top builders, protocols, and narratives.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "intelligence",
    skillId: "digest",
    inputs: [
      { key: "focus", label: "Focus area (optional)", placeholder: "e.g. DeFi protocols, AI agents, gaming" },
    ],
    isComposite: true,
    price: "$0.20",
    priceUSDC: 200000,
    x402Url: `${X402_BASE}/ecosystem-digest`,
    x402Body: (v) => ({ focus: v.focus ?? "" }),
  },
  {
    id: "market-fit",
    name: "Market Fit Validator",
    description: "Score your product's market fit with swarm intelligence across three personas.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "intelligence",
    inputs: [
      { key: "description", label: "Product description", placeholder: "What you're building, who it's for, and what problem it solves", required: true },
      { key: "stage", label: "Stage", placeholder: "e.g. idea, MVP, live product" },
    ],
    isComposite: true,
    featured: true,
    price: "$0.25",
    priceUSDC: 250000,
    x402Url: `${X402_BASE}/market-fit`,
    x402Body: (v) => ({ description: v.description ?? "", name: "", stage: v.stage ?? "idea" }),
  },
  {
    id: "token-launch-readiness",
    name: "Token Launch Readiness",
    description: "Go/no-go signal on whether your project is ready to launch a token.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "intelligence",
    inputs: [
      { key: "name", label: "Project / token name", placeholder: "e.g. $MYTOKEN or your project name", required: true },
      { key: "description", label: "Project description + traction", placeholder: "What the project does, current metrics, community size, any live product" },
    ],
    isComposite: true,
    price: "$0.30",
    priceUSDC: 300000,
    x402Url: `${X402_BASE}/token-launch-readiness`,
    x402Body: (v) => ({ name: v.name ?? "", project: v.name ?? "", description: v.description ?? "" }),
  },

  // ── Builder ─────────────────────────────────────────────────────────────────

  {
    id: "roadmap-validator",
    name: "Roadmap Validator",
    description: "Validate your roadmap against market timing, execution risk, and narrative fit.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "project", label: "Project name", placeholder: "Your project name", required: true },
      { key: "roadmap", label: "Roadmap milestones", placeholder: "Q1: X, Q2: Y, Q3: Z — be specific about what you plan to ship", required: true },
    ],
    isComposite: true,
    price: "$0.25",
    priceUSDC: 250000,
    x402Url: `${X402_BASE}/roadmap-validator`,
    x402Body: (v) => ({ project: v.project ?? "", roadmap: v.roadmap ?? "" }),
  },
  {
    id: "competitor-scan",
    name: "Competitor Scan",
    description: "Identify direct/indirect competitors and surface your defensible edge.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "project", label: "Your project", placeholder: "What you build and your main value prop", required: true },
      { key: "category", label: "Category", placeholder: "e.g. DeFi lending, AI agent, NFT marketplace" },
    ],
    isComposite: true,
    price: "$0.20",
    priceUSDC: 200000,
    x402Url: `${X402_BASE}/competitor-scan`,
    x402Body: (v) => ({ project: v.project ?? "", description: v.project ?? "", competitors: v.category ?? "" }),
  },
  {
    id: "pitch-intelligence",
    name: "Pitch Intelligence",
    description: "Transform your deck into investor-grade pitch intelligence with narrative scoring.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "project", label: "Project", placeholder: "Project name", required: true },
      { key: "description", label: "Pitch summary", placeholder: "Problem you solve, your solution, traction so far, and funding ask", required: true },
    ],
    isComposite: true,
    price: "$0.30",
    priceUSDC: 300000,
    x402Url: `${X402_BASE}/pitch-intelligence`,
    x402Body: (v) => ({ project: v.project ?? "", description: v.description ?? "" }),
  },
  {
    id: "fundraise-timing",
    name: "Fundraise Timing",
    description: "Is now the right time to raise? Market conditions, stage readiness, investor appetite.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "project", label: "Project", placeholder: "What you build", required: true },
      { key: "stage", label: "Stage & metrics", placeholder: "e.g. pre-seed, current MRR, user count, what you've shipped" },
    ],
    isComposite: true,
    price: "$0.20",
    priceUSDC: 200000,
    x402Url: `${X402_BASE}/fundraise-timing`,
    x402Body: (v) => ({ project: v.project ?? "", stage: v.stage ?? "" }),
  },
  {
    id: "gtm-brief",
    name: "GTM Brief",
    description: "Go-to-market playbook: channels, timing, messaging, and early adopter strategy.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "project", label: "Project name", placeholder: "Your project name", required: true },
      { key: "description", label: "What you're launching", placeholder: "Product description and core value prop", required: true },
      { key: "target", label: "Target audience", placeholder: "Who are your first 100 users?" },
    ],
    isComposite: true,
    price: "$0.25",
    priceUSDC: 250000,
    x402Url: `${X402_BASE}/gtm-brief`,
    x402Body: (v) => ({ project: v.project ?? "", description: v.description ?? "", target: v.target ?? "" }),
  },
  {
    id: "stack-recommender",
    name: "Stack Recommender",
    description: "Optimal tech stack for Base builders — infra, tooling, protocols, integrations.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "project_type", label: "Project type", placeholder: "e.g. DeFi protocol, AI agent, consumer app, NFT marketplace", required: true },
      { key: "constraints", label: "Constraints", placeholder: "e.g. solo dev, 2-week timeline, TypeScript only" },
    ],
    isComposite: true,
    price: "$0.20",
    priceUSDC: 200000,
    x402Url: `${X402_BASE}/stack-recommender`,
    x402Body: (v) => ({ project: v.project_type ?? "", description: v.project_type ?? "", team_size: "1", timeline: v.constraints ?? "" }),
  },
  {
    id: "investor-memo",
    name: "Investor Memo",
    description: "Full investor memo: thesis, market, moat, risks, and ask — ready to send.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "project", label: "Project name", placeholder: "Your project name", required: true },
      { key: "description", label: "Description + traction", placeholder: "What you do, current metrics, revenue, community — use real numbers", required: true },
      { key: "ask", label: "Raise ask", placeholder: "e.g. $500k pre-seed, $2M seed" },
    ],
    isComposite: true,
    featured: true,
    price: "$0.35",
    priceUSDC: 350000,
    x402Url: `${X402_BASE}/investor-memo`,
    x402Body: (v) => ({ project: v.project ?? "", description: v.description ?? "", ask: v.ask ?? "", stage: "pre-seed", traction: v.description ?? "" }),
  },
  {
    id: "agent-performance",
    name: "Agent Performance",
    description: "Benchmark your AI agent's revenue, engagement, and retention metrics.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "handle", label: "Agent X/Twitter handle", placeholder: "@yourhandle", required: true },
      { key: "repo", label: "GitHub repo (optional)", placeholder: "user/repo" },
    ],
    isComposite: true,
    price: "$0.25",
    priceUSDC: 250000,
    x402Url: `${X402_BASE}/agent-performance`,
    x402Body: (v) => ({ handle: v.handle ?? "", repo: v.repo ?? "" }),
  },
  {
    id: "agent-collab-match",
    name: "Agent Collab Match",
    description: "Find agents that complement your tool and surface collab opportunities.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "agent_a", label: "Your agent", placeholder: "Your agent name and what it does", required: true },
      { key: "agent_b", label: "Target agent", placeholder: "Agent name to evaluate collab with, or 'any'", required: true },
      { key: "collab_goal", label: "Collab goal", placeholder: "e.g. joint tool, cross-promote, revenue share" },
    ],
    isComposite: true,
    price: "$0.20",
    priceUSDC: 200000,
    x402Url: `${X402_BASE}/agent-collab-match`,
    x402Body: (v) => ({ agent_a: v.agent_a ?? "", agent_b: v.agent_b ?? "", collab_goal: v.collab_goal ?? "" }),
  },
  {
    id: "repo-health",
    name: "Repo Health",
    description: "Audit your GitHub repo health: code quality, docs, CI, contributor signals.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "repo", label: "GitHub repo", placeholder: "user/repo or full GitHub URL", required: true },
    ],
    isComposite: true,
    price: "$0.20",
    priceUSDC: 200000,
    x402Url: `${X402_BASE}/repo-health`,
    x402Body: (v) => ({ repo: v.repo ?? "", description: v.repo ?? "" }),
  },
  {
    id: "community-sentiment",
    name: "Community Sentiment",
    description: "Real-time sentiment analysis across your community channels.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "project", label: "Project / token", placeholder: "Project name or token ticker", required: true },
      { key: "channels", label: "Channels", placeholder: "e.g. Twitter @handle, Telegram link, Discord" },
    ],
    isComposite: true,
    price: "$0.20",
    priceUSDC: 200000,
    x402Url: `${X402_BASE}/community-sentiment`,
    x402Body: (v) => ({ project: v.project ?? "", description: v.channels ?? "" }),
  },
  {
    id: "defi-opportunity",
    name: "DeFi Opportunity",
    description: "Scan Base DeFi for emerging yield, liquidity, and protocol opportunities.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "focus", label: "Focus (optional)", placeholder: "e.g. stablecoin yield, LP, lending, new protocols" },
      { key: "risk_tolerance", label: "Risk tolerance", placeholder: "low / medium / high" },
    ],
    isComposite: true,
    price: "$0.25",
    priceUSDC: 250000,
    x402Url: `${X402_BASE}/defi-opportunity`,
    x402Body: (v) => ({ strategy: v.focus ?? "yield farming", risk_tolerance: v.risk_tolerance ?? "medium" }),
  },
  {
    id: "builder-deep-dd",
    name: "Builder Deep DD",
    description: "Full due diligence on a Base builder: onchain activity, shipped products, credibility.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "target", label: "Builder handle or address", placeholder: "@twitterhandle or 0x… wallet address", required: true },
    ],
    isComposite: true,
    price: "$0.35",
    priceUSDC: 350000,
    x402Url: `${X402_BASE}/builder-deep-dd`,
    x402Body: (v) => ({ target: v.target ?? "", type: "builder" }),
  },

  // ── Trading & Alpha ──────────────────────────────────────────────────────────

  {
    id: "whale-copy-signal",
    name: "Whale Copy Signal",
    description: "Track and copy high-alpha whale wallets on Base — entry, size, and timing.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "trading",
    inputs: [
      { key: "wallet", label: "Whale wallet (optional)", placeholder: "0x… leave blank to scan top Base whales" },
      { key: "token", label: "Token to watch (optional)", placeholder: "e.g. WETH, USDC, or a specific token ticker" },
    ],
    isComposite: true,
    price: "$0.25",
    priceUSDC: 250000,
    x402Url: `${X402_BASE}/whale-copy-signal`,
    x402Body: (v) => ({ wallet: v.wallet ?? "", token: v.token ?? "" }),
  },
  {
    id: "token-momentum-scanner",
    name: "Token Momentum Scanner",
    description: "Real-time momentum scan for Base tokens — breakouts, volume spikes, narrative alignment.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "trading",
    inputs: [
      { key: "timeframe", label: "Timeframe", placeholder: "e.g. 1h, 4h, 24h" },
      { key: "filter", label: "Filter", placeholder: "e.g. min $50k volume, specific narrative, mcap range" },
    ],
    isComposite: true,
    price: "$0.20",
    priceUSDC: 200000,
    x402Url: `${X402_BASE}/token-momentum-scanner`,
    x402Body: (v) => ({ chain: "base", context: `${v.timeframe ?? ""} ${v.filter ?? ""}`.trim() }),
  },

  // ── Content ─────────────────────────────────────────────────────────────────

  {
    id: "thread-intelligence",
    name: "Thread Intelligence",
    description: "Turn your alpha or project update into a high-engagement X thread.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "content",
    inputs: [
      { key: "topic", label: "Thread topic", placeholder: "What do you want to write about?", required: true },
      { key: "angle", label: "Angle", placeholder: "e.g. alpha drop, project update, educational, hot take" },
    ],
    isComposite: true,
    price: "$0.20",
    priceUSDC: 200000,
    x402Url: `${X402_BASE}/thread-intelligence`,
    x402Body: (v) => ({ topic: v.topic ?? "", audience: "Base builders", goal: v.angle ?? "" }),
  },
  {
    id: "community-growth-playbook",
    name: "Community Growth Playbook",
    description: "Proven growth tactics for Base builder communities — from 0 to 1000 members.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "content",
    inputs: [
      { key: "project", label: "Project name", placeholder: "Your project name", required: true },
      { key: "current_size", label: "Current community size", placeholder: "e.g. 50 Telegram members, 200 Twitter followers" },
    ],
    isComposite: true,
    price: "$0.25",
    priceUSDC: 250000,
    x402Url: `${X402_BASE}/community-growth-playbook`,
    x402Body: (v) => ({ project: v.project ?? "", current_size: v.current_size ?? "0", goal: "1000 active members" }),
  },

  // ── Agent Economy ────────────────────────────────────────────────────────────

  {
    id: "multi-agent-workflow",
    name: "Multi-Agent Workflow",
    description: "Design an automated workflow combining multiple agents for complex tasks.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "agent-economy",
    inputs: [
      { key: "goal", label: "Workflow goal", placeholder: "What should this workflow accomplish end-to-end?", required: true },
      { key: "agents", label: "Agents to use (optional)", placeholder: "e.g. Blue Agent, Aeon, MiroShark, or your own" },
    ],
    isComposite: true,
    price: "$0.25",
    priceUSDC: 250000,
    x402Url: `${X402_BASE}/multi-agent-workflow`,
    x402Body: (v) => ({ goal: v.goal ?? "", agents: v.agents ?? "Blue Agent, Aeon, MiroShark" }),
  },

  // ── Base Ecosystem ───────────────────────────────────────────────────────────

  {
    id: "base-grant-finder",
    name: "Base Grant Finder",
    description: "Find active grants, hackathons, and funding programs for Base builders.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "base-ecosystem",
    inputs: [
      { key: "project", label: "Project type / description", placeholder: "What you're building — be specific about the category", required: true },
      { key: "stage", label: "Stage", placeholder: "e.g. idea, MVP, live product with users" },
    ],
    isComposite: true,
    price: "$0.20",
    priceUSDC: 200000,
    x402Url: `${X402_BASE}/base-grant-finder`,
    x402Body: (v) => ({ project: v.project ?? "", stage: v.stage ?? "early", sector: "Base ecosystem" }),
  },
  {
    id: "base-protocol-comparison",
    name: "Base Protocol Comparison",
    description: "Side-by-side comparison of Base protocols for integrations and partnerships.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "base-ecosystem",
    inputs: [
      { key: "protocol_a", label: "Protocol A", placeholder: "e.g. Aerodrome, Aave, Uniswap v4", required: true },
      { key: "protocol_b", label: "Protocol B", placeholder: "e.g. Morpho, Curve, Seamless", required: true },
      { key: "use_case", label: "Your use case", placeholder: "What do you need this protocol for?" },
    ],
    isComposite: true,
    price: "$0.25",
    priceUSDC: 250000,
    x402Url: `${X402_BASE}/base-protocol-comparison`,
    x402Body: (v) => ({ protocol_a: v.protocol_a ?? "", protocol_b: v.protocol_b ?? "", category: "Base DeFi", use_case: v.use_case ?? "" }),
  },

  // ── On-chain Strategy ────────────────────────────────────────────────────────

  {
    id: "protocol-risk-monitor",
    name: "Protocol Risk Monitor",
    description: "Real-time risk assessment for your DeFi positions — exit signals, risk scores.",
    agentHandle: "composite",
    agentName: "Blue + Aeon",
    agentType: "composite",
    category: "on-chain",
    inputs: [
      { key: "protocol", label: "Protocol", placeholder: "e.g. Aerodrome, Aave Base, Uniswap v4, Morpho", required: true },
      { key: "position", label: "Position details (optional)", placeholder: "e.g. ETH/USDC LP, $5k USDC lend — helps get specific risk analysis" },
    ],
    isComposite: true,
    price: "$0.35",
    priceUSDC: 350000,
    x402Url: `${X402_BASE}/protocol-risk-monitor`,
    x402Body: (v) => ({ protocol: v.protocol ?? "", position: v.position ?? "" }),
  },

  // ── Console commands (paid x402) ────────────────────────────────────────────
  {
    id: "honeypot-check",
    name: "Honeypot Check",
    description: "Detect honeypot tokens that can be bought but not sold. Transfer tax analysis + rug pattern detection on Base.",
    agentHandle: "composite",
    agentName: "Blue + MiroShark",
    agentType: "composite",
    category: "security",
    inputs: [
      { key: "token", label: "Token contract address", placeholder: "0x...", required: true },
    ],
    isComposite: true,
    compositeSkills: [
      { agentType: "blue", label: "Honeypot detection" },
      { agentType: "miroshark", label: "Community rug signal" },
    ],
    featured: false,
    price: "$0.10", priceUSDC: 100000,
    x402Url: `https://blueagent.dev/api/x402/honeypot-check`,
    x402Body: (v) => ({ token: v.token ?? "" }),
  },
  {
    id: "risk-gate",
    name: "Risk Gate",
    description: "Pre-transaction risk assessment — screen any address or swap for drainer patterns, AML signals, and malicious contracts.",
    agentHandle: "composite",
    agentName: "Blue + MiroShark",
    agentType: "composite",
    category: "security",
    inputs: [
      { key: "to", label: "Target address", placeholder: "0x...", required: true },
      { key: "action", label: "Action type", placeholder: "transfer | swap | approve | call", required: false },
      { key: "value", label: "Amount in Wei (optional)", placeholder: "1000000000000000000", required: false },
    ],
    isComposite: true,
    compositeSkills: [
      { agentType: "blue", label: "Risk assessment" },
      { agentType: "miroshark", label: "AML + community signal" },
    ],
    featured: false,
    price: "$0.20", priceUSDC: 200000,
    x402Url: `https://blueagent.dev/api/x402/risk-gate`,
    x402Body: (v) => ({ to: v.to ?? "", action: v.action ?? "transfer", value: v.value ?? "" }),
  },
  {
    id: "deep-analysis",
    name: "Deep Analysis",
    description: "Full due diligence on any Base token — security score, market fundamentals, on-chain activity, and composite verdict.",
    agentHandle: "composite",
    agentName: "Blue + Aeon + MiroShark",
    agentType: "composite",
    category: "security",
    inputs: [
      { key: "token", label: "Token contract address", placeholder: "0x...", required: true },
      { key: "context", label: "Additional context (optional)", placeholder: "e.g. new Uniswap v4 pool token", required: false },
    ],
    isComposite: true,
    compositeSkills: [
      { agentType: "blue", label: "Security deep dive" },
      { agentType: "miroshark", label: "Market + community signal" },
      { agentType: "aeon", label: "On-chain fundamentals" },
    ],
    featured: false,
    price: "$0.50", priceUSDC: 500000,
    x402Url: `https://blueagent.dev/api/x402/deep-analysis`,
    x402Body: (v) => ({ token: v.token ?? "", context: v.context ?? "" }),
  },
  {
    id: "agent-score",
    name: "Agent Score",
    description: "Performance score for AI agents on Base — XP, interaction volume, uptime, ecosystem impact.",
    agentHandle: "composite",
    agentName: "Blue + MiroShark",
    agentType: "composite",
    category: "builder",
    inputs: [
      { key: "handle", label: "Agent handle or name", placeholder: "blueagent_", required: true },
    ],
    isComposite: true,
    compositeSkills: [
      { agentType: "blue", label: "Agent performance" },
      { agentType: "miroshark", label: "Ecosystem impact" },
    ],
    featured: false,
    price: "$0.35", priceUSDC: 350000,
    x402Url: `https://blueagent.dev/api/x402/agent-score`,
    x402Body: (v) => ({ handle: v.handle ?? "" }),
  },
  {
    id: "contract-trust",
    name: "Contract Trust",
    description: "Audit any Base contract before swapping or interacting. Basescan verification + security scan + community signal. Verdict: SAFE / CAUTION / RED_FLAG.",
    agentHandle: "composite",
    agentName: "Blue + MiroShark",
    agentType: "composite",
    category: "security",
    inputs: [
      { key: "address", label: "Contract address", placeholder: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913", required: true },
      { key: "context", label: "What is this contract? (optional)", placeholder: "USDC token on Base", required: false },
    ],
    isComposite: true,
    compositeSkills: [
      { agentType: "blue", label: "Security analysis" },
      { agentType: "miroshark", label: "Community trust signal" },
    ],
    featured: false,
    price: "$0.15", priceUSDC: 150000,
    x402Url: `https://blueagent.dev/api/x402/contract-trust`,
    x402Body: (v) => ({ address: v.address ?? "", context: v.context ?? "" }),
  },
  {
    id: "key-exposure",
    name: "Key Exposure Check",
    description: "Check if a wallet's public key is exposed on-chain (quantum vulnerability). Verdict computed from the real Base RPC nonce — never fabricated. EXPOSED means the key is visible, not that funds are at immediate risk.",
    agentHandle: "composite",
    agentName: "Blue Agent",
    agentType: "composite",
    category: "security",
    inputs: [
      { key: "address", label: "Wallet address", placeholder: "0x...", required: true },
    ],
    isComposite: true,
    price: "$0.50", priceUSDC: 500000,
    x402Url: `${X402_BASE}/key-exposure`,
    x402Body: (v) => ({ address: v.address ?? "" }),
  },
  {
    id: "blue-idea",
    name: "Blue Idea",
    description: "Turn a rough concept into a fundable brief — problem, why now, why Base, MVP scope, risks, 24h plan.",
    agentHandle: "blue", agentName: "Blue", agentType: "blue",
    category: "builder",
    inputs: [{ key: "prompt", label: "Your idea or concept", placeholder: "A USDC streaming payroll app for DAOs on Base", required: true }],
    isComposite: false,
    price: "$0.05", priceUSDC: 50000,
    x402Url: `${X402_BASE}/blue-idea`,
    x402Body: (v) => ({ prompt: v.prompt ?? "" }),
  },
  {
    id: "blue-build",
    name: "Blue Build",
    description: "Architecture, stack, folder structure, integrations, test plan. Verified Base patterns, no hallucinations.",
    agentHandle: "blue", agentName: "Blue", agentType: "blue",
    category: "builder",
    inputs: [{ key: "prompt", label: "What you're building", placeholder: "Build a token-gated API with x402 payments on Base", required: true }],
    isComposite: false,
    price: "$0.50", priceUSDC: 500000,
    x402Url: `${X402_BASE}/blue-build`,
    x402Body: (v) => ({ prompt: v.prompt ?? "" }),
  },
  {
    id: "blue-audit",
    name: "Blue Audit",
    description: "Security + product risk review. Reentrancy, oracle, MEV, x402, Coinbase Smart Wallet. Go/no-go.",
    agentHandle: "blue", agentName: "Blue", agentType: "blue",
    category: "builder",
    inputs: [{ key: "prompt", label: "Code, contract, or system to audit", placeholder: "Paste contract code or paste system description", required: true }],
    isComposite: false,
    price: "$1.00", priceUSDC: 1000000,
    x402Url: `${X402_BASE}/blue-audit`,
    x402Body: (v) => ({ prompt: v.prompt ?? "" }),
  },
  {
    id: "blue-ship",
    name: "Blue Ship",
    description: "Deployment checklist, verification, release notes, monitoring. Everything you forget when excited to launch.",
    agentHandle: "blue", agentName: "Blue", agentType: "blue",
    category: "builder",
    inputs: [{ key: "prompt", label: "What you're shipping", placeholder: "Ship my Uniswap v4 hook to Base mainnet", required: true }],
    isComposite: false,
    price: "$0.10", priceUSDC: 100000,
    x402Url: `${X402_BASE}/blue-ship`,
    x402Body: (v) => ({ prompt: v.prompt ?? "" }),
  },
  {
    id: "blue-raise",
    name: "Blue Raise",
    description: "Fundraising narrative, investor deck outline, smart money map, competitive landscape for your Base niche.",
    agentHandle: "blue", agentName: "Blue", agentType: "blue",
    category: "builder",
    inputs: [{ key: "prompt", label: "Project + raise context", placeholder: "Raise a pre-seed for my Base DeFi protocol", required: true }],
    isComposite: false,
    price: "$0.20", priceUSDC: 200000,
    x402Url: `${X402_BASE}/blue-raise`,
    x402Body: (v) => ({ prompt: v.prompt ?? "" }),
  },
  {
    id: "blue-monitor",
    name: "Blue Monitor",
    description: "On-demand health + risk snapshot for a Base token/contract — live price, liquidity, verification, risk signals, and a watch plan with alert thresholds.",
    agentHandle: "blue", agentName: "Blue", agentType: "blue",
    category: "security",
    inputs: [
      { key: "target", label: "Target", placeholder: "0x… token/contract address, or a protocol name", required: true },
      { key: "focus", label: "Focus (optional)", placeholder: "e.g. liquidity, exit risk, contract changes" },
    ],
    isComposite: false,
    price: "$0.20", priceUSDC: 200000,
    x402Url: `${X402_BASE}/blue-monitor`,
    x402Body: (v) => ({ target: v.target ?? "", focus: v.focus ?? "" }),
  },
  {
    id: "blue-registry",
    name: "Blue Registry",
    description: "Discover the Blue Hub tool catalog — every callable x402 tool (first-party + community), filterable by query/category, with prices and how-to-call.",
    agentHandle: "blue", agentName: "Blue", agentType: "blue",
    category: "builder",
    inputs: [
      { key: "query", label: "Search (optional)", placeholder: "e.g. honeypot, token, audit" },
      { key: "category", label: "Category (optional)", placeholder: "e.g. security, intelligence, builder" },
    ],
    isComposite: false,
    price: "$0.05", priceUSDC: 50000,
    x402Url: `${X402_BASE}/blue-registry`,
    x402Body: (v) => ({ query: v.query ?? "", category: v.category ?? "" }),
  },
  {
    id: "blue-research",
    name: "Blue Research",
    description: "Deep DD memo on a Base project, narrative, or token — thesis, bull/bear, risks, contrarian take, verdict. Grounds in live market data when a token address is given.",
    agentHandle: "blue", agentName: "Blue", agentType: "blue",
    category: "intelligence",
    inputs: [
      { key: "topic", label: "Topic / project", placeholder: "e.g. Base restaking, or a protocol name", required: true },
      { key: "target", label: "Token address (optional)", placeholder: "0x… to ground in live market data" },
    ],
    isComposite: false,
    price: "$1.00", priceUSDC: 1000000,
    x402Url: `${X402_BASE}/blue-research`,
    x402Body: (v) => ({ topic: v.topic ?? "", target: v.target ?? "" }),
  },
  {
    id: "blue-compose",
    name: "Blue Compose",
    description: "Turn a goal into a runnable chain of Blue Hub tools — picks from the real catalog, orders them, suggests inputs, and estimates cost.",
    agentHandle: "blue", agentName: "Blue", agentType: "blue",
    category: "builder",
    inputs: [
      { key: "goal", label: "Goal", placeholder: "e.g. take my Base DeFi idea from concept to audited + funded", required: true },
    ],
    isComposite: false,
    price: "$0.10", priceUSDC: 100000,
    x402Url: `${X402_BASE}/blue-compose`,
    x402Body: (v) => ({ goal: v.goal ?? "" }),
  },
  {
    id: "blue-deploy",
    name: "Blue Deploy",
    description: "Technical deploy mechanics for Base mainnet — deploy scripts, Basescan verify commands, env vars, gas notes, post-deploy checks. Never invents addresses.",
    agentHandle: "blue", agentName: "Blue", agentType: "blue",
    category: "builder",
    inputs: [
      { key: "project", label: "What you're deploying", placeholder: "e.g. an ERC-20 + staking contract (Foundry)", required: true },
      { key: "stack", label: "Stack (optional)", placeholder: "e.g. Foundry, Hardhat, viem" },
    ],
    isComposite: false,
    price: "$0.10", priceUSDC: 100000,
    x402Url: `${X402_BASE}/blue-deploy`,
    x402Body: (v) => ({ project: v.project ?? "", stack: v.stack ?? "" }),
  },
  {
    id: "blue-analytics",
    name: "Blue Analytics",
    description: "Performance/metrics read on a Base token — live price, momentum, liquidity health, volume/liquidity ratio, growth signals. Real DexScreener data.",
    agentHandle: "blue", agentName: "Blue", agentType: "blue",
    category: "intelligence",
    inputs: [
      { key: "target", label: "Token address", placeholder: "0x… Base token contract", required: true },
      { key: "focus", label: "Focus (optional)", placeholder: "e.g. momentum, liquidity, accumulation" },
    ],
    isComposite: false,
    price: "$0.25", priceUSDC: 250000,
    x402Url: `${X402_BASE}/blue-analytics`,
    x402Body: (v) => ({ target: v.target ?? "", focus: v.focus ?? "" }),
  },
  {
    id: "blue-simulate",
    name: "Blue Simulate",
    description: "Bull/base/bear scenario modeling for a Base decision — tokenomics, fee model, growth, runway — with assumptions, projections, and sensitivities.",
    agentHandle: "blue", agentName: "Blue", agentType: "blue",
    category: "builder",
    inputs: [
      { key: "scenario", label: "What to simulate", placeholder: "e.g. fee model at 0.3% vs 1% over 12 months", required: true },
      { key: "params", label: "Parameters (optional)", placeholder: "e.g. 10k users, $2M TVL, 5% monthly growth" },
    ],
    isComposite: false,
    price: "$0.15", priceUSDC: 150000,
    x402Url: `${X402_BASE}/blue-simulate`,
    x402Body: (v) => ({ scenario: v.scenario ?? "", params: v.params ?? "" }),
  },
  {
    id: "blue-stream",
    name: "Blue Stream",
    description: "Live snapshot feed of onchain activity on Base or Robinhood Chain — trending & new pools, TVL, real price/volume/liquidity. Pure real data, poll for a near-real-time feed.",
    agentHandle: "blue", agentName: "Blue", agentType: "blue",
    category: "on-chain",
    inputs: [
      { key: "feed", label: "Feed", placeholder: "movers | new | all (default: movers)" },
      { key: "chain", label: "Chain", placeholder: "base | robinhood (default: base)" },
    ],
    isComposite: false,
    price: "$0.05", priceUSDC: 50000,
    x402Url: `${X402_BASE}/blue-stream`,
    x402Body: (v) => ({ feed: v.feed ?? "movers", chain: v.chain ?? "base" }),
  },

  {
    id: "aml-screen",
    name: "AML Screen",
    description: "AML compliance screening for any wallet — transaction patterns, risk flags, clean/suspicious verdict.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "on-chain",
    inputs: [
      { key: "address", label: "Wallet address to screen", placeholder: "0x...", required: true },
    ],
    isComposite: true,
    price: "$0.25", priceUSDC: 250000,
    x402Url: `${X402_BASE}/aml-screen`,
    x402Body: (v) => ({ address: v.address ?? "" }),
  },
  {
    id: "airdrop-check",
    name: "Airdrop Check",
    description: "Base airdrop eligibility check — which protocols, activity score, estimated value.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "on-chain",
    inputs: [
      { key: "address", label: "Wallet address", placeholder: "0x...", required: true },
    ],
    isComposite: true,
    price: "$0.10", priceUSDC: 100000,
    x402Url: `${X402_BASE}/airdrop-check`,
    x402Body: (v) => ({ address: v.address ?? "" }),
  },
  {
    id: "whale-tracker",
    name: "Whale Tracker",
    description: "Smart money and whale flow analysis — accumulation vs distribution signal for any token.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "on-chain",
    inputs: [
      { key: "address", label: "Token or wallet address", placeholder: "0x...", required: true },
    ],
    isComposite: true,
    price: "$0.10", priceUSDC: 100000,
    x402Url: `${X402_BASE}/whale-tracker`,
    x402Body: (v) => ({ address: v.address ?? "" }),
  },
  {
    id: "dex-flow",
    name: "DEX Flow",
    description: "DEX volume, buy/sell pressure and liquidity flow for any Base token — live DexScreener data.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "on-chain",
    inputs: [
      { key: "token", label: "Token contract address or ticker", placeholder: "0x... or BRETT", required: true },
    ],
    isComposite: true,
    price: "$0.15", priceUSDC: 150000,
    x402Url: `${X402_BASE}/dex-flow`,
    x402Body: (v) => ({ token: v.token ?? "" }),
  },

  // ── Earn ─────────────────────────────────────────────────────────────────────

  {
    id: "lp-analyzer",
    name: "LP Analyzer",
    description: "LP position analysis — impermanent loss, fee income, rebalance recommendation.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "earn",
    inputs: [
      { key: "token0", label: "Token 0", placeholder: "ETH or 0x...", required: true },
      { key: "token1", label: "Token 1", placeholder: "USDC or 0x..." },
      { key: "entryPrice", label: "Entry price (optional)", placeholder: "e.g. 2400" },
      { key: "investedAmount", label: "Invested amount USD (optional)", placeholder: "e.g. 5000" },
    ],
    isComposite: true,
    price: "$0.25", priceUSDC: 250000,
    x402Url: `${X402_BASE}/lp-analyzer`,
    x402Body: (v) => ({ token0: v.token0 ?? "", token1: v.token1 ?? "", entryPrice: v.entryPrice ?? "", investedAmount: v.investedAmount ?? "" }),
  },

  // ── Alerts ───────────────────────────────────────────────────────────────────


  // ── Builder (launch & grants) ─────────────────────────────────────────────────

  {
    id: "launch-simulator-1",
    name: "Launch Simulator Tier 1",
    description: "Quick Signal — baseline ecosystem read + 3-agent verdict. Fast pre-launch gut-check.",
    agentHandle: "composite", agentName: "Blue + Aeon + MiroShark", agentType: "composite",
    category: "builder",
    inputs: [
      { key: "project", label: "Project name", placeholder: "Your project name", required: true },
      { key: "description", label: "Project description", placeholder: "What it does, target audience, current stage" },
      { key: "ticker", label: "Token ticker (optional)", placeholder: "e.g. $BLUEAGENT" },
    ],
    isComposite: true,
    price: "$0.10", priceUSDC: 100000,
    x402Url: `${X402_BASE}/launch-simulator-1`,
    x402Body: (v) => ({ project: v.project ?? "", description: v.description ?? "", ticker: v.ticker ?? "" }),
  },
  {
    id: "launch-simulator-2",
    name: "Launch Simulator Tier 2",
    description: "Deep Signal launch simulation with live DexScreener market data — price, volume, liquidity.",
    agentHandle: "composite", agentName: "Blue + Aeon + MiroShark", agentType: "composite",
    category: "builder",
    inputs: [
      { key: "project", label: "Project name", placeholder: "Your project name", required: true },
      { key: "description", label: "Project description", placeholder: "What it does, target audience, current stage" },
      { key: "ticker", label: "Token ticker (optional)", placeholder: "e.g. $BLUEAGENT" },
      { key: "contract", label: "Contract address (optional)", placeholder: "0x... for live market data" },
    ],
    isComposite: true,
    price: "$0.35", priceUSDC: 350000,
    x402Url: `${X402_BASE}/launch-simulator-2`,
    x402Body: (v) => ({ project: v.project ?? "", description: v.description ?? "", ticker: v.ticker ?? "", contract: v.contract ?? "" }),
  },
  {
    id: "launch-simulator-3",
    name: "Launch Simulator Tier 3",
    description: "Full Simulation — complete multi-agent report with risk matrix and timeline recommendation.",
    agentHandle: "composite", agentName: "Blue + Aeon + MiroShark", agentType: "composite",
    category: "builder",
    inputs: [
      { key: "project", label: "Project name", placeholder: "Your project name", required: true },
      { key: "description", label: "Project description", placeholder: "What it does, target audience, current stage" },
      { key: "ticker", label: "Token ticker (optional)", placeholder: "e.g. $BLUEAGENT" },
      { key: "contract", label: "Contract address (optional)", placeholder: "0x... for live market data" },
    ],
    isComposite: true,
    featured: true,
    price: "$0.50", priceUSDC: 500000,
    x402Url: `${X402_BASE}/launch-simulator-3`,
    x402Body: (v) => ({ project: v.project ?? "", description: v.description ?? "", ticker: v.ticker ?? "", contract: v.contract ?? "" }),
  },
  {
    id: "grant-evaluator",
    name: "Grant Evaluator",
    description: "Base ecosystem grant scoring — innovation, feasibility, impact, team quality.",
    agentHandle: "composite", agentName: "Blue Agent", agentType: "composite",
    category: "builder",
    inputs: [
      { key: "projectName", label: "Project name", placeholder: "Your project name", required: true },
      { key: "description", label: "Project description", placeholder: "What you're building and why it matters for Base", required: true },
      { key: "teamBackground", label: "Team background (optional)", placeholder: "Experience, previous projects, GitHub" },
      { key: "requestedAmount", label: "Requested grant amount (optional)", placeholder: "e.g. $25,000" },
      { key: "milestones", label: "Milestones (optional)", placeholder: "What you'll deliver and when" },
      { key: "githubUrl", label: "GitHub URL (optional)", placeholder: "https://github.com/..." },
    ],
    isComposite: true,
    price: "$5.00", priceUSDC: 5000000,
    x402Url: `${X402_BASE}/grant-evaluator`,
    x402Body: (v) => ({ projectName: v.projectName ?? "", description: v.description ?? "", teamBackground: v.teamBackground ?? "", requestedAmount: v.requestedAmount ?? "", milestones: v.milestones ?? "", githubUrl: v.githubUrl ?? "" }),
  },

  // ── Feed scan tools (internal — power Blue Feed v2) ──────────────────────────

  {
    id: "base-token-scan",
    name: "Base Token Scan",
    description: "Hard-filter token scan on Base — 5 quality gates (vol, liquidity, depth ratio, momentum, scam filter). Returns ≤ 3 grounded signals only. No LLM.",
    agentHandle: "blueagent", agentName: "Blue Agent", agentType: "blue",
    category: "signal",
    inputs: [],
    isComposite: false,
    price: "$0.05", priceUSDC: 50000,
    x402Url: `${X402_BASE}/base-token-scan`,
    x402Body: () => ({}),
  },
  {
    id: "defi-yield-scan",
    name: "DeFi Yield Scan",
    description: "Hard-filter DeFi yield scan on Base — deduped by protocol, APY ≥ 4%, TVL ≥ $500K. Returns top 5 live opportunities. No LLM.",
    agentHandle: "blueagent", agentName: "Blue Agent", agentType: "blue",
    category: "earn",
    inputs: [],
    isComposite: false,
    price: "$0.05", priceUSDC: 50000,
    x402Url: `${X402_BASE}/defi-yield-scan`,
    x402Body: () => ({}),
  },
  {
    id: "narrative-scan",
    name: "Narrative Scan",
    description: "Detects active Base narratives from real trending token data. Tracks Emerging → Rising → Peak → Fading lifecycle in KV. Venice LLM grounded by GeckoTerminal.",
    agentHandle: "blueagent", agentName: "Blue Agent", agentType: "blue",
    category: "signal",
    inputs: [],
    isComposite: false,
    price: "$0.10", priceUSDC: 100000,
    x402Url: `${X402_BASE}/narrative-scan`,
    x402Body: () => ({}),
  },
  {
    id: "picks-check",
    name: "Signal Track Record",
    description: "Measures base-token-scan signal filter accuracy 22h after detection. WIN/LOSS = filter direction correct, not trading profit. Not financial advice.",
    agentHandle: "blueagent", agentName: "Blue Agent", agentType: "blue",
    category: "signal",
    inputs: [],
    isComposite: false,
    price: "$0.05", priceUSDC: 50000,
    x402Url: `${X402_BASE}/picks-check`,
    x402Body: () => ({}),
  },

  // ─── RH RWA Phase 1 — Robinhood Chain tokenized-stock primitives ────────
  // Canonical registry + Chainlink oracle + fuzzy search + anti-scam verify.
  // Data: docs.robinhood.com/chain/contracts + Chainlink RH mainnet feeds.
  // Public-good primitive layer for every builder embedding RH stock tokens.
  {
    id: "rh-stock-token",
    name: "RH Stock Token Lookup",
    description: "Canonical Robinhood Chain (4663) tokenized-stock lookup. Input a ticker (MSTR, AAPL, TSLA) or company name → contract address, decimals, Chainlink oracle price + DEX spot cross-check + Blockscout link. Real data only (docs.robinhood.com + Chainlink AggregatorV3 + GeckoTerminal).",
    agentHandle: "blueagent", agentName: "Blue Agent", agentType: "blue",
    category: "on-chain",
    inputs: [
      { key: "query", label: "Ticker or company name", placeholder: "MSTR, AAPL, Tesla", required: true },
    ],
    isComposite: false,
    price: "$0.05", priceUSDC: 50000,
    x402Url: `${X402_BASE}/rh-stock-token`,
    x402Body: (v) => ({ query: v.query ?? "" }),
  },
  {
    id: "rh-rwa-index",
    name: "RH RWA Index",
    description: "Full canonical Robinhood Chain RWA catalog — 20+ tokenized stocks, 5 ETFs, plus Chainlink-only feeds. Zero-input. For portfolio dashboards + sector basket builders.",
    agentHandle: "blueagent", agentName: "Blue Agent", agentType: "blue",
    category: "on-chain",
    inputs: [],
    isComposite: false,
    price: "$0.02", priceUSDC: 20000,
    x402Url: `${X402_BASE}/rh-rwa-index`,
    x402Body: () => ({}),
  },
  {
    id: "rh-stock-search",
    name: "RH Stock Search",
    description: "Fuzzy search across the canonical Robinhood Chain RWA registry. Typo-tolerant (Levenshtein + prefix). Returns top-N ranked matches. Never fabricates a contract address.",
    agentHandle: "blueagent", agentName: "Blue Agent", agentType: "blue",
    category: "on-chain",
    inputs: [
      { key: "query", label: "Partial ticker or name", placeholder: "micro, tesla, appl", required: true },
      { key: "limit", label: "Max matches (optional)", placeholder: "5" },
    ],
    isComposite: false,
    price: "$0.02", priceUSDC: 20000,
    x402Url: `${X402_BASE}/rh-stock-search`,
    x402Body: (v) => ({ query: v.query ?? "", limit: v.limit ? Number(v.limit) : 5 }),
  },
  {
    id: "rh-rwa-verify",
    name: "RH RWA Verify (Anti-Scam)",
    description: "Given a contract address on Robinhood Chain, is it a canonical RHJ-issued stock token or an impersonator? Cross-checks registry + live ERC-20 metadata. Surfaces the real contract when a fake claims a matching ticker. Free — safety checks should never be gated.",
    agentHandle: "blueagent", agentName: "Blue Agent", agentType: "blue",
    category: "security",
    inputs: [
      { key: "contract", label: "Contract address", placeholder: "0x…", required: true },
      { key: "expected_ticker", label: "Expected ticker (optional)", placeholder: "MSTR" },
    ],
    isComposite: false,
    price: "$0.00", priceUSDC: 0,
    x402Url: `${X402_BASE}/rh-rwa-verify`,
    x402Body: (v) => ({ contract: v.contract ?? "", expected_ticker: v.expected_ticker ?? "" }),
  },
  {
    id: "rh-stock-quote",
    name: "RH Stock Quote (Chainlink)",
    description: "Deterministic live quote for Robinhood Chain tokenized stocks. On-chain Chainlink AggregatorV3 latestRoundData → raw answer + decimals + updatedAt + staleness. Falls back to DEX spot only if no feed exists. The one embed-friendly price tool.",
    agentHandle: "blueagent", agentName: "Blue Agent", agentType: "blue",
    category: "on-chain",
    inputs: [
      { key: "ticker", label: "Ticker", placeholder: "MSTR, AAPL, TSLA", required: true },
    ],
    isComposite: false,
    price: "$0.03", priceUSDC: 30000,
    x402Url: `${X402_BASE}/rh-stock-quote`,
    x402Body: (v) => ({ ticker: v.ticker ?? "" }),
  },

  // ─── RH RWA Phase 2 — Market Analytics ─────────────────────────────────
  {
    id: "rh-stock-ohlc",
    name: "RH Stock OHLC",
    description: "OHLC candle history for a Robinhood Chain tokenized stock. Timeframes: minute / hour / day. Backed by GeckoTerminal pool history — deepest-liquidity pool auto-selected. Returns candles + summary (high, low, total volume, % change).",
    agentHandle: "blueagent", agentName: "Blue Agent", agentType: "blue",
    category: "on-chain",
    inputs: [
      { key: "ticker",    label: "Ticker",    placeholder: "MSTR, AAPL, TSLA", required: true },
      { key: "timeframe", label: "Timeframe", placeholder: "minute / hour / day (default hour)" },
      { key: "limit",     label: "Limit",     placeholder: "100 (max 500)" },
    ],
    isComposite: false,
    price: "$0.05", priceUSDC: 50000,
    x402Url: `${X402_BASE}/rh-stock-ohlc`,
    x402Body: (v) => ({
      ticker: v.ticker ?? "",
      timeframe: v.timeframe ?? "hour",
      limit: v.limit ? Number(v.limit) : 100,
    }),
  },
  {
    id: "rh-stock-liquidity",
    name: "RH Stock Liquidity",
    description: "Live DEX pool + TVL + slippage estimate for a Robinhood Chain tokenized stock. All pools sorted by liquidity + first-order slippage estimates at $100 / $1k / $10k / $100k trade sizes. Real reserves, no LLM.",
    agentHandle: "blueagent", agentName: "Blue Agent", agentType: "blue",
    category: "on-chain",
    inputs: [
      { key: "ticker", label: "Ticker", placeholder: "MSTR, AAPL, TSLA", required: true },
    ],
    isComposite: false,
    price: "$0.05", priceUSDC: 50000,
    x402Url: `${X402_BASE}/rh-stock-liquidity`,
    x402Body: (v) => ({ ticker: v.ticker ?? "" }),
  },
  {
    id: "rh-stock-movers",
    name: "RH Stock Movers",
    description: "Top gainers / losers 24h among Robinhood Chain tokenized stocks & ETFs. Cross-references DEX pool data against the canonical RWA registry — no non-RWA pools contaminate the ranking. Returns empty if <3 pools with reported change.",
    agentHandle: "blueagent", agentName: "Blue Agent", agentType: "blue",
    category: "signal",
    inputs: [
      { key: "limit", label: "Limit per side (optional)", placeholder: "5" },
    ],
    isComposite: false,
    price: "$0.05", priceUSDC: 50000,
    x402Url: `${X402_BASE}/rh-stock-movers`,
    x402Body: (v) => ({ limit: v.limit ? Number(v.limit) : 5 }),
  },
  {
    id: "rh-stock-arb",
    name: "RH Stock Arb (Chainlink vs DEX)",
    description: "Deterministic arbitrage delta for a Robinhood Chain tokenized stock: Chainlink oracle vs deepest DEX pool spot. Returns absolute Δ, pct Δ, and a hard-mapped verdict (ALIGNED / LONG_DEX / SHORT_DEX). Real trading signal.",
    agentHandle: "blueagent", agentName: "Blue Agent", agentType: "blue",
    category: "signal",
    inputs: [
      { key: "ticker", label: "Ticker", placeholder: "MSTR, AAPL, TSLA", required: true },
    ],
    isComposite: false,
    price: "$0.05", priceUSDC: 50000,
    x402Url: `${X402_BASE}/rh-stock-arb`,
    x402Body: (v) => ({ ticker: v.ticker ?? "" }),
  },
];

// ─── v2 defaults ──────────────────────────────────────────────────────────────
// Centralize verified/aiReady/builder defaults so we don't have to set them on
// every tool. Builder-submitted tools (Phase 3) override these explicitly.

const DEFAULT_RELEASED_AT = new Date("2024-06-01T00:00:00Z").getTime();

function withV2Defaults(t: AgentTool): AgentTool {
  return {
    ...t,
    verified:       t.verified       ?? true,            // first-party = pre-verified
    aiReady:        t.aiReady        ?? true,            // all current tools return JSON
    builderAddress: t.builderAddress ?? BLUE_TREASURY,
    releasedAt:     t.releasedAt     ?? DEFAULT_RELEASED_AT,
  };
}

export const AGENT_TOOLS: AgentTool[] = AGENT_TOOLS_RAW.map(withV2Defaults);
