// Blue Agent x402 API — local-dev server (separate surface from the apps/web Hub).
// Every handler here is a thin proxy → blueagent.dev/api/x402/<id> (single source
// of truth). Bankr x402 Cloud collects USDC payment, forwards to these handlers,
// which proxy upstream with the X-Blue-Internal bypass. Production paid x402 is
// served by Bankr x402 Cloud; blueagent.dev runs the actual tool compute.
//
// AUTO-GENERATED by _gen.mjs from apps/web AGENT_TOOLS — do not edit by hand.
import { config } from "dotenv";
config();

import http from 'http';
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

import agentCollabMatch from './x402/agent-collab-match/index.js';
import agentPerformance from './x402/agent-performance/index.js';
import agentReadiness from './x402/agent-readiness/index.js';
import agentScore from './x402/agent-score/index.js';
import airdropCheck from './x402/airdrop-check/index.js';
import amlScreen from './x402/aml-screen/index.js';
import b20Check from './x402/b20-check/index.js';
import baseActivityScore from './x402/base-activity-score/index.js';
import baseAlpha from './x402/base-alpha/index.js';
import baseGrantFinder from './x402/base-grant-finder/index.js';
import baseProtocolComparison from './x402/base-protocol-comparison/index.js';
import basePulse from './x402/base-pulse/index.js';
import blueAnalytics from './x402/blue-analytics/index.js';
import blueAudit from './x402/blue-audit/index.js';
import blueBuild from './x402/blue-build/index.js';
import blueCompose from './x402/blue-compose/index.js';
import blueDeploy from './x402/blue-deploy/index.js';
import blueIdea from './x402/blue-idea/index.js';
import blueMonitor from './x402/blue-monitor/index.js';
import blueRaise from './x402/blue-raise/index.js';
import blueRegistry from './x402/blue-registry/index.js';
import blueResearch from './x402/blue-research/index.js';
import blueShip from './x402/blue-ship/index.js';
import blueSimulate from './x402/blue-simulate/index.js';
import blueStream from './x402/blue-stream/index.js';
import builderDeepDd from './x402/builder-deep-dd/index.js';
import communityGrowthPlaybook from './x402/community-growth-playbook/index.js';
import communitySentiment from './x402/community-sentiment/index.js';
import competitorScan from './x402/competitor-scan/index.js';
import contractTrust from './x402/contract-trust/index.js';
import crossProtocolYield from './x402/cross-protocol-yield/index.js';
import deepAnalysis from './x402/deep-analysis/index.js';
import defiOpportunity from './x402/defi-opportunity/index.js';
import dexFlow from './x402/dex-flow/index.js';
import ecosystemDigest from './x402/ecosystem-digest/index.js';
import founderCheck from './x402/founder-check/index.js';
import fundraiseTiming from './x402/fundraise-timing/index.js';
import gasTracker from './x402/gas-tracker/index.js';
import grantEvaluator from './x402/grant-evaluator/index.js';
import gtmBrief from './x402/gtm-brief/index.js';
import honeypotCheck from './x402/honeypot-check/index.js';
import investorMemo from './x402/investor-memo/index.js';
import keyExposure from './x402/key-exposure/index.js';
import launchSimulator1 from './x402/launch-simulator-1/index.js';
import launchSimulator2 from './x402/launch-simulator-2/index.js';
import launchSimulator3 from './x402/launch-simulator-3/index.js';
import liquidityDepth from './x402/liquidity-depth/index.js';
import lpAnalyzer from './x402/lp-analyzer/index.js';
import marketFit from './x402/market-fit/index.js';
import multiAgentWorkflow from './x402/multi-agent-workflow/index.js';
import narrativePosition from './x402/narrative-position/index.js';
import narrativePulse from './x402/narrative-pulse/index.js';
import newPools from './x402/new-pools/index.js';
import pitchIntelligence from './x402/pitch-intelligence/index.js';
import poolScan from './x402/pool-scan/index.js';
import protocolHealth from './x402/protocol-health/index.js';
import protocolRiskMonitor from './x402/protocol-risk-monitor/index.js';
import quickSafety from './x402/quick-safety/index.js';
import repoHealth from './x402/repo-health/index.js';
import riskGate from './x402/risk-gate/index.js';
import roadmapValidator from './x402/roadmap-validator/index.js';
import scamDetector from './x402/scam-detector/index.js';
import stackRecommender from './x402/stack-recommender/index.js';
import threadIntelligence from './x402/thread-intelligence/index.js';
import tokenAlpha from './x402/token-alpha/index.js';
import tokenDistribution from './x402/token-distribution/index.js';
import tokenLaunchReadiness from './x402/token-launch-readiness/index.js';
import tokenMomentumScanner from './x402/token-momentum-scanner/index.js';
import tokenPickSignal from './x402/token-pick-signal/index.js';
import tokenPrice from './x402/token-price/index.js';
import walletHoldings from './x402/wallet-holdings/index.js';
import walletRisk from './x402/wallet-risk/index.js';
import whaleCopySignal from './x402/whale-copy-signal/index.js';
import whaleTracker from './x402/whale-tracker/index.js';

const PORT = parseInt(process.env.PORT ?? '3001', 10);

const HANDLERS: Record<string, (req: Request) => Promise<Response>> = {
  'agent-collab-match': agentCollabMatch,
  'agent-performance': agentPerformance,
  'agent-readiness': agentReadiness,
  'agent-score': agentScore,
  'airdrop-check': airdropCheck,
  'aml-screen': amlScreen,
  'b20-check': b20Check,
  'base-activity-score': baseActivityScore,
  'base-alpha': baseAlpha,
  'base-grant-finder': baseGrantFinder,
  'base-protocol-comparison': baseProtocolComparison,
  'base-pulse': basePulse,
  'blue-analytics': blueAnalytics,
  'blue-audit': blueAudit,
  'blue-build': blueBuild,
  'blue-compose': blueCompose,
  'blue-deploy': blueDeploy,
  'blue-idea': blueIdea,
  'blue-monitor': blueMonitor,
  'blue-raise': blueRaise,
  'blue-registry': blueRegistry,
  'blue-research': blueResearch,
  'blue-ship': blueShip,
  'blue-simulate': blueSimulate,
  'blue-stream': blueStream,
  'builder-deep-dd': builderDeepDd,
  'community-growth-playbook': communityGrowthPlaybook,
  'community-sentiment': communitySentiment,
  'competitor-scan': competitorScan,
  'contract-trust': contractTrust,
  'cross-protocol-yield': crossProtocolYield,
  'deep-analysis': deepAnalysis,
  'defi-opportunity': defiOpportunity,
  'dex-flow': dexFlow,
  'ecosystem-digest': ecosystemDigest,
  'founder-check': founderCheck,
  'fundraise-timing': fundraiseTiming,
  'gas-tracker': gasTracker,
  'grant-evaluator': grantEvaluator,
  'gtm-brief': gtmBrief,
  'honeypot-check': honeypotCheck,
  'investor-memo': investorMemo,
  'key-exposure': keyExposure,
  'launch-simulator-1': launchSimulator1,
  'launch-simulator-2': launchSimulator2,
  'launch-simulator-3': launchSimulator3,
  'liquidity-depth': liquidityDepth,
  'lp-analyzer': lpAnalyzer,
  'market-fit': marketFit,
  'multi-agent-workflow': multiAgentWorkflow,
  'narrative-position': narrativePosition,
  'narrative-pulse': narrativePulse,
  'new-pools': newPools,
  'pitch-intelligence': pitchIntelligence,
  'pool-scan': poolScan,
  'protocol-health': protocolHealth,
  'protocol-risk-monitor': protocolRiskMonitor,
  'quick-safety': quickSafety,
  'repo-health': repoHealth,
  'risk-gate': riskGate,
  'roadmap-validator': roadmapValidator,
  'scam-detector': scamDetector,
  'stack-recommender': stackRecommender,
  'thread-intelligence': threadIntelligence,
  'token-alpha': tokenAlpha,
  'token-distribution': tokenDistribution,
  'token-launch-readiness': tokenLaunchReadiness,
  'token-momentum-scanner': tokenMomentumScanner,
  'token-pick-signal': tokenPickSignal,
  'token-price': tokenPrice,
  'wallet-holdings': walletHoldings,
  'wallet-risk': walletRisk,
  'whale-copy-signal': whaleCopySignal,
  'whale-tracker': whaleTracker,
};

const __dir = dirname(fileURLToPath(import.meta.url));
let services: Record<string, unknown> = {};
try {
  services = JSON.parse(readFileSync(join(__dir, 'bankr.x402.json'), 'utf8'));
} catch {}

function setCors(res: http.ServerResponse) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, X-Payment, x-api-key, Authorization');
}

const server = http.createServer(async (req, res) => {
  setCors(res);
  if (req.method === 'OPTIONS') { res.writeHead(204); res.end(); return; }

  const url = new URL(req.url ?? '/', `http://localhost:${PORT}`);
  const toolId = url.pathname.split('/').filter(Boolean)[0];

  if (!toolId || req.method === 'GET') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      name: 'blue-agent-x402', version: '0.2.0',
      tools: Object.keys(HANDLERS), count: Object.keys(HANDLERS).length, services,
    }, null, 2));
    return;
  }

  const handler = HANDLERS[toolId];
  if (!handler) {
    res.writeHead(404, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: `Unknown tool: ${toolId}` }));
    return;
  }

  const chunks: Buffer[] = [];
  for await (const chunk of req) chunks.push(chunk as Buffer);
  const body = Buffer.concat(chunks).toString();

  try {
    const webReq = new Request(`http://localhost:${PORT}${req.url}`, {
      method: req.method ?? 'GET',
      headers: req.headers as Record<string, string>,
      body: req.method !== 'GET' && req.method !== 'HEAD' && body ? body : null,
    });
    const webRes = await handler(webReq);
    const responseBody = await webRes.text();
    const ct = webRes.headers.get('content-type') ?? 'application/json';
    res.writeHead(webRes.status, { 'Content-Type': ct });
    res.end(responseBody);
  } catch (err) {
    console.error(`[${toolId}] Error:`, err);
    res.writeHead(500, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Internal error', message: (err as Error).message }));
  }
});

server.listen(PORT, () => {
  console.log(`\n🔵 Blue Agent x402 API (proxy layer) — http://localhost:${PORT}`);
  console.log(`   ${Object.keys(HANDLERS).length} proxied services\n`);
});
